<?xml version="1.0" ?>
<!DOCTYPE main [
  <!ELEMENT main (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (IDECADASTRO?,MANDATOSCD?,MANDATOSEXTERNOS?,NUMGABINETE?,ANEXO?,ANDAR?,TELEFONE?,FAX?,CODPESSOA?,TXTNOMEPARLAMENTAR?,TXTNOME?,INDSEXO?,NUMCARTEIRAPARLAMENTAR?,NUMERODAULTIMALEGISLATURA?,SIGPARTIDO?,SIGUFREPRESENTACAO?,DATNASCIMENTO?,GRAUINSTRUCAO?,NATURALIDADE?,PROFISSOES?,FILIACAO?,CONJUGE?,FILHOS?,LEGISLATURAS?,MANDATOSELETIVOS?,FILIACOESPARTIDARIAS?,AFASTAMENTOS?,SUPLENCIASEFETIVACOES?,LICENCAS?,PERDASMANDATO?,RENUNCIAS?,ATIVIDADESPARTIDARIAS?,ATIVIDADESPROFISSIONAIS?,ESTUDOSEGRAUSUNIVERSITARIOS?,SEMINARIOS?,ATIVIDADESPARLAMENTARES?,ATIVIDADESSINDICAIS?,CONSELHOS?,CONDECORACOES?,OBRASPUBLICADAS?,MISSOESOFICIAS?,OUTRASINFORMACOES?,FORMATODATANASCIMENTO?)+>
  <!ELEMENT IDECADASTRO (#PCDATA)>
  <!ELEMENT MANDATOSCD (#PCDATA)>
  <!ELEMENT MANDATOSEXTERNOS (#PCDATA)>
  <!ELEMENT NUMGABINETE (#PCDATA)>
  <!ELEMENT ANEXO (#PCDATA)>
  <!ELEMENT ANDAR (#PCDATA)>
  <!ELEMENT TELEFONE (#PCDATA)>
  <!ELEMENT FAX (#PCDATA)>
  <!ELEMENT CODPESSOA (#PCDATA)>
  <!ELEMENT TXTNOMEPARLAMENTAR (#PCDATA)>
  <!ELEMENT TXTNOME (#PCDATA)>
  <!ELEMENT INDSEXO (#PCDATA)>
  <!ELEMENT NUMCARTEIRAPARLAMENTAR (#PCDATA)>
  <!ELEMENT NUMERODAULTIMALEGISLATURA (#PCDATA)>
  <!ELEMENT SIGPARTIDO (#PCDATA)>
  <!ELEMENT SIGUFREPRESENTACAO (#PCDATA)>
  <!ELEMENT DATNASCIMENTO (#PCDATA)>
  <!ELEMENT GRAUINSTRUCAO (#PCDATA)>
  <!ELEMENT NATURALIDADE (#PCDATA)>
  <!ELEMENT PROFISSOES (#PCDATA)>
  <!ELEMENT FILIACAO (#PCDATA)>
  <!ELEMENT CONJUGE (#PCDATA)>
  <!ELEMENT FILHOS (#PCDATA)>
  <!ELEMENT LEGISLATURAS (#PCDATA)>
  <!ELEMENT MANDATOSELETIVOS (#PCDATA)>
  <!ELEMENT FILIACOESPARTIDARIAS (#PCDATA)>
  <!ELEMENT AFASTAMENTOS (#PCDATA)>
  <!ELEMENT SUPLENCIASEFETIVACOES (#PCDATA)>
  <!ELEMENT LICENCAS (#PCDATA)>
  <!ELEMENT PERDASMANDATO (#PCDATA)>
  <!ELEMENT RENUNCIAS (#PCDATA)>
  <!ELEMENT ATIVIDADESPARTIDARIAS (#PCDATA)>
  <!ELEMENT ATIVIDADESPROFISSIONAIS (#PCDATA)>
  <!ELEMENT ESTUDOSEGRAUSUNIVERSITARIOS (#PCDATA)>
  <!ELEMENT SEMINARIOS (#PCDATA)>
  <!ELEMENT ATIVIDADESPARLAMENTARES (#PCDATA)>
  <!ELEMENT ATIVIDADESSINDICAIS (#PCDATA)>
  <!ELEMENT CONSELHOS (#PCDATA)>
  <!ELEMENT CONDECORACOES (#PCDATA)>
  <!ELEMENT OBRASPUBLICADAS (#PCDATA)>
  <!ELEMENT MISSOESOFICIAS (#PCDATA)>
  <!ELEMENT OUTRASINFORMACOES (#PCDATA)>
  <!ELEMENT FORMATODATANASCIMENTO (#PCDATA)>
]>
<main>
  <DATA_RECORD>
    <IDECADASTRO>2903</IDECADASTRO>
    <MANDATOSCD>Deputado Federal, 1935-1937, RS, FUG. Dt. Posse: 19/06/1935.</MANDATOSCD>
    <CODPESSOA>126191</CODPESSOA>
    <TXTNOMEPARLAMENTAR>OSCAR FONTOURA</TXTNOMEPARLAMENTAR>
    <TXTNOME>Oscar Carneiro da Fontoura</TXTNOME>
    <INDSEXO>M</INDSEXO>
    <NUMERODAULTIMALEGISLATURA>37</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>FUG</SIGPARTIDO>
    <SIGUFREPRESENTACAO>RS</SIGUFREPRESENTACAO>
    <NATURALIDADE>Dom Pedrito, RS</NATURALIDADE>
    <PROFISSOES>M&#233;dico e Pecuarista</PROFISSOES>
    <CONJUGE>Alice Machado Fontoura</CONJUGE>
    <LEGISLATURAS>1935-1937</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, 1935-1937, RS, FUG. Dt. Posse: 19/06/1935.</MANDATOSELETIVOS>
    <FILIACOESPARTIDARIAS>FUG; PSD, 1945-.</FILIACOESPARTIDARIAS>
    <ATIVIDADESPROFISSIONAIS>Secret&#225;rio Estadual da Fazenda, 1937-1945, 1951-1955; Secret&#225;rio do Interior e Justi&#231;a, 1947-1951.</ATIVIDADESPROFISSIONAIS>
    <ATIVIDADESSINDICAIS>Um dos fundadores e Presidente &#40;1963-1964&#41;, Federa&#231;&#227;o de Agricultura do Rio Grande do Sul.</ATIVIDADESSINDICAIS>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDECADASTRO>2905</IDECADASTRO>
    <MANDATOSCD>Deputado Federal, 1935-1937, RJ, UPF. Dt. Posse: 02/05/1935.</MANDATOSCD>
    <CODPESSOA>126249</CODPESSOA>
    <TXTNOMEPARLAMENTAR>AGENOR RABELO</TXTNOMEPARLAMENTAR>
    <TXTNOME>Agenor Ferreira Rabelo</TXTNOME>
    <INDSEXO>M</INDSEXO>
    <NUMERODAULTIMALEGISLATURA>37</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>SEM PARTIDO</SIGPARTIDO>
    <SIGUFREPRESENTACAO>RJ</SIGUFREPRESENTACAO>
    <DATNASCIMENTO>21/12/94</DATNASCIMENTO>
    <NATURALIDADE>N&#227;o informado, RJ</NATURALIDADE>
    <LEGISLATURAS>1935-1937</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, 1935-1937, RJ, UPF. Dt. Posse: 02/05/1935.</MANDATOSELETIVOS>
    <FILIACOESPARTIDARIAS>UPF</FILIACOESPARTIDARIAS>
    <ATIVIDADESPROFISSIONAIS>Desembargador, RJ.</ATIVIDADESPROFISSIONAIS>
    <ATIVIDADESPARLAMENTARES>C&#194;MARA DOS DEPUTADOS:&#10;MESA DIRETORA: 2&#186; Secret&#225;rio, 1935; 3&#186; Secret&#225;rio, 1936, 1937.</ATIVIDADESPARLAMENTARES>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDECADASTRO>2906</IDECADASTRO>
    <MANDATOSCD>Deputado Federal, 1935-1937, RJ, UPF. Dt. Posse: 02/05/1935.</MANDATOSCD>
    <MANDATOSEXTERNOS>Senador Suplente, RJ, Partido: PTB,&#10;Per&#237;odo: 1959 a 1959</MANDATOSEXTERNOS>
    <CODPESSOA>126250</CODPESSOA>
    <TXTNOMEPARLAMENTAR>BANDEIRA VAUGHAN</TXTNOMEPARLAMENTAR>
    <TXTNOME>Raimundo Bandeira Vaughan</TXTNOME>
    <INDSEXO>M</INDSEXO>
    <NUMERODAULTIMALEGISLATURA>37</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>UPF</SIGPARTIDO>
    <SIGUFREPRESENTACAO>RJ</SIGUFREPRESENTACAO>
    <DATNASCIMENTO>04/10/89</DATNASCIMENTO>
    <NATURALIDADE>, </NATURALIDADE>
    <FILIACAO>Raimundo Carneiro de Sousa Bandeira e Helena Vaughan Bandeira</FILIACAO>
    <CONJUGE>Maria Jos&#233; Monnerat Bandeira Vaughan</CONJUGE>
    <LEGISLATURAS>1935-1937</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, 1935-1937, RJ, UPF. Dt. Posse: 02/05/1935; Senador Suplente, 1959, RJ, PTB.</MANDATOSELETIVOS>
    <FILIACOESPARTIDARIAS>UPF; PTB; PDC; UDN</FILIACOESPARTIDARIAS>
    <ATIVIDADESPROFISSIONAIS>Secret&#225;rio de Energia El&#233;trica e Desenvolvimento Econ&#244;mico do estado do Rio de Janeiro, 1959-1961.</ATIVIDADESPROFISSIONAIS>
    <OBRASPUBLICADAS>Livro da fam&#237;lia Monnerat, 1945; &#193;rvore geneal&#243;gica das fam&#237;lias Busle e Dubeaux; &#193;rvore geneal&#243;gica de Manuel Bandeira; Leveduras e Fermenta&#231;&#227;o Alc&#243;olica; Cultura do Eucalipto e Carv&#227;o Vegetal.</OBRASPUBLICADAS>
    <OUTRASINFORMACOES>Concorreu &#224;s elei&#231;&#245;es de maio de 1933 para a Assembl&#233;ia Nacional Constituinte pelo Rio de Jeneiro na legenda da Uni&#227;o Progressista Fluminense, obtendo apenas a 4&#170; Supl&#234;ncia. Em 1950, candidatou-se a Deputado Federal pelo Rio de Janeiro na legenda da Uni&#227;o Democr&#225;tica Nacional &#40;UDN&#41;, obtendo apenas a uma supl&#234;ncia. Voltou a candidatar-se no pleito de outubro de 1954, dessa vez pelo Partido Democrata Crist&#227;o &#40;PDC&#41;, obtendo nova supl&#234;ncia. Em outubro de 1958 elegeu-se suplente do Senador Miguel Cout</OUTRASINFORMACOES>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDECADASTRO>2907</IDECADASTRO>
    <MANDATOSCD>Deputado Federal, 1935-1937, RJ, UPF. Dt. Posse: 02/05/1935.</MANDATOSCD>
    <CODPESSOA>126251</CODPESSOA>
    <TXTNOMEPARLAMENTAR>BENTO COSTA</TXTNOMEPARLAMENTAR>
    <TXTNOME>Bento Costa J&#250;nior</TXTNOME>
    <INDSEXO>M</INDSEXO>
    <NUMERODAULTIMALEGISLATURA>37</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>UPF</SIGPARTIDO>
    <SIGUFREPRESENTACAO>RJ</SIGUFREPRESENTACAO>
    <NATURALIDADE>, </NATURALIDADE>
    <LEGISLATURAS>1935-1937</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, 1935-1937, RJ, UPF. Dt. Posse: 02/05/1935.</MANDATOSELETIVOS>
    <PERDASMANDATO>Perdeu o mandato de Deputado Federal, na Legislatura 1935-1937, em 10 de novembro de 1937, em virtude da implanta&#231;&#227;o do Estado Novo que suprimiu os &#243;rg&#227;os legislativos do pa&#237;s.</PERDASMANDATO>
    <CONSELHOS>Membro, Conselho Diretor da Federa&#231;&#227;o Industrial do Rio de Janeiro, 1931-1934.</CONSELHOS>
    <OUTRASINFORMACOES>Candidatou-se Deputado Federal &#224; Assembl&#233;ia Nacional Constituinte pelo estado do Rio de Janeiro na legenda da Uni&#227;o Progressista Fluminense, UFP, em 1933, ficando como s&#233;timo suplente da bancada.</OUTRASINFORMACOES>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDECADASTRO>2908</IDECADASTRO>
    <MANDATOSCD>Deputado Federal, 1935-1937, RJ, UPF. Dt. Posse: 02/05/1935.</MANDATOSCD>
    <CODPESSOA>126252</CODPESSOA>
    <TXTNOMEPARLAMENTAR>CARDILHO FILHO</TXTNOMEPARLAMENTAR>
    <TXTNOME>Joaquim Cardilho Filho</TXTNOME>
    <INDSEXO>M</INDSEXO>
    <NUMERODAULTIMALEGISLATURA>37</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>UPF</SIGPARTIDO>
    <SIGUFREPRESENTACAO>RJ</SIGUFREPRESENTACAO>
    <DATNASCIMENTO>29/11/06</DATNASCIMENTO>
    <NATURALIDADE>Barra Mansa, RJ</NATURALIDADE>
    <LEGISLATURAS>1935-1937</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, 1935-1937, RJ, UPF. Dt. Posse: 02/05/1935.</MANDATOSELETIVOS>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDECADASTRO>2910</IDECADASTRO>
    <MANDATOSCD>Deputado Federal, 1935-1937, RJ, UPF. Dt. Posse: 04/05/1935.</MANDATOSCD>
    <CODPESSOA>126255</CODPESSOA>
    <TXTNOMEPARLAMENTAR>LONTRA COSTA</TXTNOMEPARLAMENTAR>
    <TXTNOME>Artur Lontra Costa</TXTNOME>
    <INDSEXO>M</INDSEXO>
    <NUMERODAULTIMALEGISLATURA>37</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>UPF</SIGPARTIDO>
    <SIGUFREPRESENTACAO>RJ</SIGUFREPRESENTACAO>
    <DATNASCIMENTO>19/05/99</DATNASCIMENTO>
    <GRAUINSTRUCAO>Superior</GRAUINSTRUCAO>
    <NATURALIDADE>Campos, RJ</NATURALIDADE>
    <FILIACAO>Artur Emiliano Costa e Mariana Ribeiro Lontra Costa</FILIACAO>
    <CONJUGE>Edite Fernandes de Lontra Costa</CONJUGE>
    <LEGISLATURAS>1935-1937</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, 1935-1937, RJ, UPF. Dt. Posse: 04/05/1935.</MANDATOSELETIVOS>
    <FILIACOESPARTIDARIAS>UPF, -1937; UDB, 1937-.</FILIACOESPARTIDARIAS>
    <ATIVIDADESPARTIDARIAS>Um dos fundadores, Esquerda Democr&#225;tica, posteriormente Partido Socialista Brasileiro &#40;PSB&#41;.</ATIVIDADESPARTIDARIAS>
    <ESTUDOSEGRAUSUNIVERSITARIOS>Ci&#234;ncias Jur&#237;dicas, Fac. de Direito, Rio de Janeiro, 1922.</ESTUDOSEGRAUSUNIVERSITARIOS>
    <ATIVIDADESPARLAMENTARES>C&#194;MARA DOS DEPUTADOS:&#10;CD:&#10;COMISS&#213;ES: Educa&#231;&#227;o e Cultura.</ATIVIDADESPARLAMENTARES>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDECADASTRO>2911</IDECADASTRO>
    <MANDATOSCD>Deputado Federal, 1935-1937, SC, PLC. Dt. Posse: 02/05/1935.</MANDATOSCD>
    <CODPESSOA>126265</CODPESSOA>
    <TXTNOMEPARLAMENTAR>DINIZ J&#218;NIOR</TXTNOMEPARLAMENTAR>
    <TXTNOME>Leopoldo de Diniz Martins J&#250;nior</TXTNOME>
    <INDSEXO>M</INDSEXO>
    <NUMERODAULTIMALEGISLATURA>37</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>PLC</SIGPARTIDO>
    <SIGUFREPRESENTACAO>SC</SIGUFREPRESENTACAO>
    <DATNASCIMENTO>02/09/89</DATNASCIMENTO>
    <GRAUINSTRUCAO>Superior</GRAUINSTRUCAO>
    <NATURALIDADE>Florian&#243;polis, SC</NATURALIDADE>
    <PROFISSOES>Jornalista, Diplomata e Promotor P&#250;blico</PROFISSOES>
    <FILIACAO>Leopoldo Diniz Martins e Maria Ant&#244;nia Medeiros dos Santos Martins</FILIACAO>
    <LEGISLATURAS>1935-1937</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, 1935-1937, SC, PLC. Dt. Posse: 02/05/1935.</MANDATOSELETIVOS>
    <ATIVIDADESPARTIDARIAS>Membro, Estado-Maior da A&#231;&#227;o Social Brasileira &#40;Partido Nacional Facista&#41;; Membro, Partido Liberal Catarinense.</ATIVIDADESPARTIDARIAS>
    <ATIVIDADESPROFISSIONAIS>Promotor P&#250;blico, Laguna, SC, 1910-1913; Inspetor Escolar, 1914; Secret&#225;rio do Prefeito do Distrito Federal e Presidente da Comiss&#227;o de Or&#231;amento de Prefeitura do Distrito Federal, 1930; Superinten</ATIVIDADESPROFISSIONAIS>
    <ESTUDOSEGRAUSUNIVERSITARIOS>Fac. de Direito de S&#227;o Paulo, 1909.</ESTUDOSEGRAUSUNIVERSITARIOS>
    <ATIVIDADESPARLAMENTARES>C&#194;MARA DOS DEPUTADOS:&#10;CD: &#10;COMISS&#213;ES: de Diplomacia e Tratados da C&#226;mara, Membro e Presidente.</ATIVIDADESPARLAMENTARES>
    <ATIVIDADESSINDICAIS>Presidente, Instituto nacional do Mate, 1938-1941.</ATIVIDADESSINDICAIS>
    <CONSELHOS>Conselheiro Comercial do Minist&#233;rio das Rela&#231;&#245;es Exteriores.</CONSELHOS>
    <MISSOESOFICIAS>Representante do Brasil na Comiss&#227;o Mista Comercial Brasil-Argentina, Buenos Aires, 1942-1946 e 1956-1959.</MISSOESOFICIAS>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDECADASTRO>2913</IDECADASTRO>
    <MANDATOSCD>Deputado Federal, 1935-1937, SP, PC. Dt. Posse: 06/05/1935.</MANDATOSCD>
    <MANDATOSEXTERNOS>Prefeito, SP, Partido: PC,&#10;Per&#237;odo:  a </MANDATOSEXTERNOS>
    <CODPESSOA>126273</CODPESSOA>
    <TXTNOMEPARLAMENTAR>BOTELHO EGAS</TXTNOMEPARLAMENTAR>
    <TXTNOME>Jos&#233; Maria Botelho  Egas</TXTNOME>
    <INDSEXO>M</INDSEXO>
    <NUMERODAULTIMALEGISLATURA>37</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>PC</SIGPARTIDO>
    <SIGUFREPRESENTACAO>SP</SIGUFREPRESENTACAO>
    <DATNASCIMENTO>26/08/98</DATNASCIMENTO>
    <NATURALIDADE>S&#227;o Paulo, SP</NATURALIDADE>
    <PROFISSOES>M&#233;dico</PROFISSOES>
    <FILIACAO>Eug&#234;nio Egas e C&#226;ndida Botelho Egas</FILIACAO>
    <CONJUGE>Olga Botelho Egas</CONJUGE>
    <LEGISLATURAS>1935-1937</LEGISLATURAS>
    <MANDATOSELETIVOS>Prefeito, , , SP, PC; Deputado Federal, 1935-1937, SP, PC. Dt. Posse: 06/05/1935.</MANDATOSELETIVOS>
    <ESTUDOSEGRAUSUNIVERSITARIOS>Medicina, Universidade de S&#227;o Paulo, 1927.</ESTUDOSEGRAUSUNIVERSITARIOS>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDECADASTRO>2914</IDECADASTRO>
    <MANDATOSCD>Deputado Federal, 1935-1937, SP, PRP. Dt. Posse: 02/05/1935.</MANDATOSCD>
    <CODPESSOA>126274</CODPESSOA>
    <TXTNOMEPARLAMENTAR>CASTRO PRADO</TXTNOMEPARLAMENTAR>
    <TXTNOME>Cid Bierrembach de  Castro Prado</TXTNOME>
    <INDSEXO>M</INDSEXO>
    <NUMERODAULTIMALEGISLATURA>37</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>PRP</SIGPARTIDO>
    <SIGUFREPRESENTACAO>SP</SIGUFREPRESENTACAO>
    <DATNASCIMENTO>05/08/95</DATNASCIMENTO>
    <GRAUINSTRUCAO>Superior</GRAUINSTRUCAO>
    <NATURALIDADE>Campinas, SP</NATURALIDADE>
    <PROFISSOES>Advogado, Jornalista e Historiador</PROFISSOES>
    <FILIACAO>Ant&#244;nio de Castro Prado e Albertina Bierrembach de Castro Prado</FILIACAO>
    <CONJUGE>Laura Bierrembach de Castro Prado</CONJUGE>
    <FILHOS>Maria Teresa de Castro Prado Coutinho Nogueira</FILHOS>
    <LEGISLATURAS>1935-1937</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, 1935-1937, SP, PRP. Dt. Posse: 02/05/1935.</MANDATOSELETIVOS>
    <ATIVIDADESPROFISSIONAIS>Promotor P&#250;blico, Comarca de Batatais, SP; Oficial do Registro de Im&#243;veis da 12&#170; Circunscri&#231;&#227;o.</ATIVIDADESPROFISSIONAIS>
    <ESTUDOSEGRAUSUNIVERSITARIOS>Col&#233;gio S&#227;o Lu&#237;s de Itu, SP; Fac. de Direito de S&#227;o Paulo.</ESTUDOSEGRAUSUNIVERSITARIOS>
    <OBRASPUBLICADAS>A eloq&#252;&#234;ncia de C&#233;sar Bierrembach, 1947; Viagem &#224; Bahia, 1950; Martim Francisco, 1966.</OBRASPUBLICADAS>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDECADASTRO>2915</IDECADASTRO>
    <MANDATOSCD>Deputado Federal, 1937-1937, SP, . Dt. Posse: 06/01/1937.</MANDATOSCD>
    <MANDATOSEXTERNOS>Vereador, S&#227;o Carlos/SP, Partido: N/D,&#10;Per&#237;odo:  a </MANDATOSEXTERNOS>
    <CODPESSOA>126275</CODPESSOA>
    <TXTNOMEPARLAMENTAR>DAGOBERTO SALES</TXTNOMEPARLAMENTAR>
    <TXTNOME>Dagoberto  Sales</TXTNOME>
    <INDSEXO>M</INDSEXO>
    <NUMERODAULTIMALEGISLATURA>37</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>SEM PARTIDO</SIGPARTIDO>
    <SIGUFREPRESENTACAO>SP</SIGUFREPRESENTACAO>
    <DATNASCIMENTO>05/03/84</DATNASCIMENTO>
    <NATURALIDADE>Rio Claro, SP</NATURALIDADE>
    <PROFISSOES>Advogado, Serventu&#225;rio da Justi&#231;a e Promotor P&#250;blico</PROFISSOES>
    <FILIACAO>Joaquim Augusto de Sales e Francisca Negreiros Sales</FILIACAO>
    <CONJUGE>Judite Penido Monteiro</CONJUGE>
    <FILHOS>Dagoberto Sales Filho</FILHOS>
    <LEGISLATURAS>1935-1937</LEGISLATURAS>
    <MANDATOSELETIVOS>Vereador, , S&#227;o Carlos, SP, ; Deputado Federal, 1937-1937, SP, . Dt. Posse: 06/01/1937.</MANDATOSELETIVOS>
    <ATIVIDADESPARTIDARIAS>Um dos fundadores, Partido Constitucionalista de S&#227;o Paulo.</ATIVIDADESPARTIDARIAS>
    <ATIVIDADESPROFISSIONAIS>Advogado e Serventu&#225;rio da Justi&#231;a, S&#227;o Paulo, SP; Advogado, S&#227;o Carlos, SP; Lente, Escola Normal do munic&#237;pio, S&#227;o Carlos, SP; Delegado de Pol&#237;cia, Ja&#250;, SP; Promotor P&#250;blico, Itatiba e S&#227;o Carlos,</ATIVIDADESPROFISSIONAIS>
    <ESTUDOSEGRAUSUNIVERSITARIOS>Instituto Feitosa; Col&#233;gio S&#227;o Paulo e Minas; Col&#233;gio Jo&#227;o de Deus, SP; Fac. de Direito, SP, 1905.</ESTUDOSEGRAUSUNIVERSITARIOS>
    <ATIVIDADESPARLAMENTARES>C&#194;MARAS MUNICIPAIS, ASSEMBL&#201;IAS LEGISLATIVAS E C&#194;MARA LEGISLATIVA:&#10;CMSP: Presidente.&#10;ALSP: Deputado, 1929.</ATIVIDADESPARLAMENTARES>
    <ATIVIDADESSINDICAIS>Membro, Instituto Hist&#243;rico e Geogr&#225;fico de S&#227;o Paulo.</ATIVIDADESSINDICAIS>
    <OUTRASINFORMACOES>Seu tio, Manuel Ferraz de Campos Sales, foi Presidente da Rep&#250;blica, 1898-1902. Seu filho, Dagoberto Sales Filho, foi Deputado Federal por S&#227;o Paulo, 1955-1959 e 1960-1962.</OUTRASINFORMACOES>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDECADASTRO>2916</IDECADASTRO>
    <MANDATOSCD>Deputado Federal, 1935-1937, SP, . Dt. Posse: 02/05/1935.</MANDATOSCD>
    <CODPESSOA>126276</CODPESSOA>
    <TXTNOMEPARLAMENTAR>F&#193;BIO ARANHA</TXTNOMEPARLAMENTAR>
    <TXTNOME>F&#225;bio Correia de Camargo Aranha</TXTNOME>
    <INDSEXO>M</INDSEXO>
    <NUMERODAULTIMALEGISLATURA>37</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>UDB</SIGPARTIDO>
    <SIGUFREPRESENTACAO>SP</SIGUFREPRESENTACAO>
    <DATNASCIMENTO>01/01/89</DATNASCIMENTO>
    <GRAUINSTRUCAO>Superior</GRAUINSTRUCAO>
    <NATURALIDADE>Rio Claro, SP</NATURALIDADE>
    <PROFISSOES>Advogado</PROFISSOES>
    <FILIACAO>Jos&#233; Correia de Camargo Aranha e Ol&#237;via Meira de Camargo Aranha</FILIACAO>
    <CONJUGE>Mercedes Guimar&#227;es de Camargo Aranha</CONJUGE>
    <LEGISLATURAS>1935-1937</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, 1935-1937, SP, . Dt. Posse: 02/05/1935.</MANDATOSELETIVOS>
    <ATIVIDADESPARTIDARIAS>Membro, Diret&#243;rio do PD durante o VII Congresso do partido, realizado em fevereiro de 1931.</ATIVIDADESPARTIDARIAS>
    <ESTUDOSEGRAUSUNIVERSITARIOS>Fac. de Direito do largo do S&#227;o Francisco, 1915.</ESTUDOSEGRAUSUNIVERSITARIOS>
    <FORMATODATANASCIMENTO>3</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDECADASTRO>2921</IDECADASTRO>
    <MANDATOSCD>Deputado Federal, 1935-1937, SP, . Dt. Posse: 02/05/1935.</MANDATOSCD>
    <CODPESSOA>126282</CODPESSOA>
    <TXTNOMEPARLAMENTAR>JOS&#201; C&#193;SSIO</TXTNOMEPARLAMENTAR>
    <TXTNOME>Jos&#233; C&#225;ssio de Macedo Soares</TXTNOME>
    <INDSEXO>M</INDSEXO>
    <NUMERODAULTIMALEGISLATURA>37</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>SEM PARTIDO</SIGPARTIDO>
    <SIGUFREPRESENTACAO>SP</SIGUFREPRESENTACAO>
    <DATNASCIMENTO>01/01/89</DATNASCIMENTO>
    <GRAUINSTRUCAO>Superior</GRAUINSTRUCAO>
    <NATURALIDADE>Piratininga, SP</NATURALIDADE>
    <PROFISSOES>Professor</PROFISSOES>
    <FILIACAO>Jos&#233; Eduardo de Macedo Soares e C&#226;ndida Azevedo Sodr&#233; de Macedo Soares</FILIACAO>
    <LEGISLATURAS>1935-1937</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, 1935-1937, SP, . Dt. Posse: 02/05/1935.</MANDATOSELETIVOS>
    <ATIVIDADESPROFISSIONAIS>Professor, Curso de Medicina, Universidade de S&#227;o Paulo; Superintendente, Companhia de Seguros A S&#227;o Paulo; Presidente, Companhia Agr&#237;cola Araqu&#225;; Diretor, Departamento de Assist&#234;ncia Social; Membr</ATIVIDADESPROFISSIONAIS>
    <ESTUDOSEGRAUSUNIVERSITARIOS>Escola de Farm&#225;cia e Odontologia de S&#227;o Paulo, 1908; Fac. de Medicina do Rio de Janeiro, 1913.</ESTUDOSEGRAUSUNIVERSITARIOS>
    <ATIVIDADESSINDICAIS>Diretor, Sociedade Rural Brasileira; Diretor, Federa&#231;&#227;o dos Criadores de Bovinos; Organizador, Escola Profissional Feminina, Asilo Santo Ant&#244;nio de Araras; Diretor-Tesoureiro, Insti</ATIVIDADESSINDICAIS>
    <OBRASPUBLICADAS>Estudo da hist&#243;ria da lepra em S&#227;o Paulo, 1925.</OBRASPUBLICADAS>
    <OUTRASINFORMACOES>Sua fam&#237;lia teve atua&#231;&#227;o destacada na vida pol&#237;tica e cultural do pa&#237;s: seu av&#244;, Joaquim Mariano de Azevedo Soares, foi fazendeiro e aristocrata rural fluminense e seu tio, o conselheiro Ant&#244;nio Joaquim de Macedo Soares, foi ministro do Supremo Tribunal Federal &#40;STF&#41;, 1892-1905. Entre seus irm&#227;os sobressa&#237;ram Jos&#233; Carlos de Macedo Soares, Deputado &#224; Constituinte de 1934, ministro das Rela&#231;&#245;es Exteriores, 1934-1937, 1955-1958, ministro da Justi&#231;a, 1937 e interventor federal em S&#227;o Paulo, 1945-1947</OUTRASINFORMACOES>
    <FORMATODATANASCIMENTO>3</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDECADASTRO>2928</IDECADASTRO>
    <MANDATOSCD>Deputado Federal, 1935-1937, SP, PRP. Dt. Posse: 14/05/1935.</MANDATOSCD>
    <CODPESSOA>126291</CODPESSOA>
    <TXTNOMEPARLAMENTAR>TEIXEIRA PINTO</TXTNOMEPARLAMENTAR>
    <TXTNOME>&#193;lvaro Teixeira Pinto Filho</TXTNOME>
    <INDSEXO>M</INDSEXO>
    <NUMERODAULTIMALEGISLATURA>37</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>PRP</SIGPARTIDO>
    <SIGUFREPRESENTACAO>SP</SIGUFREPRESENTACAO>
    <NATURALIDADE>, </NATURALIDADE>
    <LEGISLATURAS>1935-1937</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, 1935-1937, SP, PRP. Dt. Posse: 14/05/1935.</MANDATOSELETIVOS>
    <OUTRASINFORMACOES>Informa&#231;&#245;es retiradas do Dicion&#225;rio Hist&#243;rico-Biogr&#225;fico Brasileiro, p&#243;s-1930, ed. FGV, Rio de Janeiro, vol. IV, 2001.</OUTRASINFORMACOES>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDECADASTRO>2931</IDECADASTRO>
    <MANDATOSCD>Deputado Federal, 3/5/1935 a 10/11/1937, , . Dt. Posse: 02/05/1935.</MANDATOSCD>
    <CODPESSOA>126294</CODPESSOA>
    <TXTNOMEPARLAMENTAR>ARLINDO PINTO</TXTNOMEPARLAMENTAR>
    <TXTNOME>Arlindo Ferreira Leite Pinto</TXTNOME>
    <INDSEXO>M</INDSEXO>
    <NUMERODAULTIMALEGISLATURA>37</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>SEM PARTIDO</SIGPARTIDO>
    <NATURALIDADE>, </NATURALIDADE>
    <LEGISLATURAS>1935-1937</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, 3/5/1935 a 10/11/1937, , . Dt. Posse: 02/05/1935.</MANDATOSELETIVOS>
    <PERDASMANDATO>Perdeu o mandato de Deputado Federal na Legislatura 1935-1937, em 10 de novembro de 1937, em virtude da implanta&#231;&#227;o do Estado Novo que suprimiu os &#243;rg&#227;os legislativos do pa&#237;s.</PERDASMANDATO>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDECADASTRO>2932</IDECADASTRO>
    <MANDATOSCD>Deputado Federal, 1935-1937, , . Dt. Posse: 02/05/1935.</MANDATOSCD>
    <CODPESSOA>126295</CODPESSOA>
    <TXTNOMEPARLAMENTAR>FRAN&#199;A FILHO</TXTNOMEPARLAMENTAR>
    <TXTNOME>Ant&#244;nio Ribeiro Fran&#231;a Filho</TXTNOME>
    <INDSEXO>M</INDSEXO>
    <NUMERODAULTIMALEGISLATURA>37</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>SEM PARTIDO</SIGPARTIDO>
    <DATNASCIMENTO>10/12/05</DATNASCIMENTO>
    <GRAUINSTRUCAO>Superior</GRAUINSTRUCAO>
    <NATURALIDADE>Rio de Janeiro, RJ</NATURALIDADE>
    <PROFISSOES>Industrial e Comerciante</PROFISSOES>
    <FILIACAO>Ant&#244;nio Ribeiro Fran&#231;a e Am&#233;lia Oliveira dos Santos Fran&#231;a</FILIACAO>
    <CONJUGE>Elvira Caldeira Fran&#231;a</CONJUGE>
    <LEGISLATURAS>1935-1937</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, 1935-1937, , . Dt. Posse: 02/05/1935.</MANDATOSELETIVOS>
    <ATIVIDADESPROFISSIONAIS>Propriet&#225;rio, Confeitaria Colombo, Rio de Janeiro; Presidente, Companhia Agr&#237;cola Industrial Colombo; Presidente, Usina A&#231;ucareira Porto Real; Diretor, Companhia Nacional de Engenharia e Arquitetur</ATIVIDADESPROFISSIONAIS>
    <ESTUDOSEGRAUSUNIVERSITARIOS>Prim&#225;rio e Secund&#225;rio, Externato Santo Ant&#244;nio Maria Zacarias, RJ; Escola de Ci&#234;ncias Jur&#237;dicas e Sociais, RJ.</ESTUDOSEGRAUSUNIVERSITARIOS>
    <ATIVIDADESPARLAMENTARES>C&#194;MARA DOS DEPUTADOS:&#10;CD:&#10;COMISS&#195;O: Finan&#231;as.</ATIVIDADESPARLAMENTARES>
    <ATIVIDADESSINDICAIS>Um dos fundadores, Diretor, Presidente &#40;1933-1934&#41;, Sindicato dos Lojistas do Rio de Janeiro; Membro da junta diretiva provis&#243;ria, Confedera&#231;&#227;o Nacional do Com&#233;rcio; Diretor, Associ</ATIVIDADESSINDICAIS>
    <CONSELHOS>Membro, Conselho Nacional do Trabalho, 1935-1945.</CONSELHOS>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDECADASTRO>2933</IDECADASTRO>
    <MANDATOSCD>Deputado Federal, 1935-1937, , . Dt. Posse: 02/05/1935.</MANDATOSCD>
    <CODPESSOA>126296</CODPESSOA>
    <TXTNOMEPARLAMENTAR>GAST&#195;O VIDIGAL</TXTNOMEPARLAMENTAR>
    <TXTNOME>Gast&#227;o Vidigal</TXTNOME>
    <INDSEXO>M</INDSEXO>
    <NUMERODAULTIMALEGISLATURA>37</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>SEM PARTIDO</SIGPARTIDO>
    <NATURALIDADE>, </NATURALIDADE>
    <LEGISLATURAS>1935-1937</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, 1935-1937, , . Dt. Posse: 02/05/1935.</MANDATOSELETIVOS>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDECADASTRO>2935</IDECADASTRO>
    <MANDATOSCD>Deputado Federal, 1935-1937, , . Dt. Posse: 02/05/1935.</MANDATOSCD>
    <CODPESSOA>126298</CODPESSOA>
    <TXTNOMEPARLAMENTAR>LE&#212;NCIO ARA&#218;JO</TXTNOMEPARLAMENTAR>
    <TXTNOME>Le&#244;ncio Gomes de Ara&#250;jo</TXTNOME>
    <INDSEXO>M</INDSEXO>
    <NUMERODAULTIMALEGISLATURA>37</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>SEM PARTIDO</SIGPARTIDO>
    <NATURALIDADE>, </NATURALIDADE>
    <LEGISLATURAS>1935-1937</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, 1935-1937, , . Dt. Posse: 02/05/1935.</MANDATOSELETIVOS>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDECADASTRO>2937</IDECADASTRO>
    <MANDATOSCD>Deputado Federal, 1935-1937, RJ, . Dt. Posse: 02/05/1935.</MANDATOSCD>
    <CODPESSOA>126300</CODPESSOA>
    <TXTNOMEPARLAMENTAR>VICENTE GALLIEZ</TXTNOMEPARLAMENTAR>
    <TXTNOME>Vicente de Paulo Galliez</TXTNOME>
    <INDSEXO>M</INDSEXO>
    <NUMERODAULTIMALEGISLATURA>37</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>SEM PARTIDO</SIGPARTIDO>
    <SIGUFREPRESENTACAO>RJ</SIGUFREPRESENTACAO>
    <DATNASCIMENTO>06/03/03</DATNASCIMENTO>
    <GRAUINSTRUCAO>Superior</GRAUINSTRUCAO>
    <NATURALIDADE>Petr&#243;polis, RJ</NATURALIDADE>
    <PROFISSOES>Industrial, Advogado, Comerciante e Segurador</PROFISSOES>
    <FILIACAO>Carlos J&#250;lio Galliez e Clara Mendes da Luz Galliez</FILIACAO>
    <CONJUGE>Gilda L&#250;cia de Sousa Witte Galliez</CONJUGE>
    <LEGISLATURAS>1935-1937</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, 1935-1937, RJ, . Dt. Posse: 02/05/1935.</MANDATOSELETIVOS>
    <ATIVIDADESPROFISSIONAIS>Presindente, Distribuidora de Comest&#237;veis Disco; Presidente, Companhia de Seguros Gerais &#40;Independ&#234;ncia&#41;; Presidente, Minera&#231;&#227;o Sertaneja; Presidente, Brasimet Com&#233;rcio e Ind&#250;stria; Presidente, Exc</ATIVIDADESPROFISSIONAIS>
    <ESTUDOSEGRAUSUNIVERSITARIOS>Externato Santo Ant&#244;nio Maria Zacarias; Ci&#234;ncias Jur&#237;dicas e Sociais, Fac. de Direito da Universidade do Rio de Janeiro, 1925.</ESTUDOSEGRAUSUNIVERSITARIOS>
    <ATIVIDADESSINDICAIS>Um dos fundadores, Confedera&#231;&#227;o Industrial do Brasil &#40;CIB&#41;; Presidente, Sindicato das Empresas de Privados e de Capitaliza&#231;&#227;o do Rio de Janeiro, 1952-1956 e 1963-1965; Presidente, F</ATIVIDADESSINDICAIS>
    <CONSELHOS>Membro, Conselho Diretor da Federa&#231;&#227;o Industrial do Rio de Janeiro &#40;FIRJ&#41;, 1931-1936; Membro, Conselho Nacional do Trabalho, 1943-1945; Presidente, Conselho de Contribuintes do Minist&#233;rio da Fazenda; Membro, Conselho Superior do Com&#233;rcio e Ind&#250;stria; Membro, Conselho de representantes da Federa&#231;&#227;o das Ind&#250;strias da Guanabara, Membro, Centro Industrial do Rio de Janeiro; Participou dos conselhos fiscais da Brasp&#233;rola Ind&#250;stria e Com&#233;rcio, da F&#225;brica de Fil&#243;, da F&#225;brica de Rendas Arp, da Malharia A</CONSELHOS>
    <MISSOESOFICIAS>Delegado do Brasil, Confer&#234;ncia Interamericana do Trabalho, Santiago, Chile, 1935, Genebra, Su&#237;&#231;a, 1936,1937, 1938, Havana, Cuba, 1939, Calif&#243;rnia, S&#227;o Francisco, EUA, 1948, Rio de Janeiro, 1952; Membro da Delega&#231;&#227;o Brasileira, Confer&#226;ncia das Na&#231;&#245;es Unidas, S&#227;o Francisco, Calif&#243;rnia, EUA, 1945; Membro da Delega&#231;&#227;o Brasileira, IV Confer&#234;ncia Hemisf&#233;rica de Seguros, Nova Iorque, EUA, 1952; Presidente, I Confer&#234;ncia Brasileira de Seguros Privados, Rio de Janeiro, RJ, 1953; Presidente, V Confer&#234;ncia</MISSOESOFICIAS>
    <OUTRASINFORMACOES>Contraiu segundas n&#250;pcias com Gilda L&#250;cia de Sousa Witte Galliez.&#10;&#10;Algumas informa&#231;&#245;es retiradas do Dicion&#225;rio Hist&#243;rico-Biogr&#225;fico Brasileiro, p&#243;s-1930, ed. FGV, Rio de Janeiro, vol. II, 2001.</OUTRASINFORMACOES>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDECADASTRO>2938</IDECADASTRO>
    <MANDATOSCD>Deputado Federal, 1935-1937, , . Dt. Posse: 02/05/1935.</MANDATOSCD>