<?xml version="1.0" ?>
<!DOCTYPE main [
  <!ELEMENT main (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (IDECADASTRO?,MANDATOSCD?,MANDATOSEXTERNOS?,NUMGABINETE?,ANEXO?,ANDAR?,TELEFONE?,FAX?,CODPESSOA?,TXTNOMEPARLAMENTAR?,TXTNOME?,INDSEXO?,NUMCARTEIRAPARLAMENTAR?,NUMERODAULTIMALEGISLATURA?,SIGPARTIDO?,SIGUFREPRESENTACAO?,DATNASCIMENTO?,GRAUINSTRUCAO?,NATURALIDADE?,PROFISSOES?,FILIACAO?,CONJUGE?,FILHOS?,LEGISLATURAS?,MANDATOSELETIVOS?,FILIACOESPARTIDARIAS?,AFASTAMENTOS?,SUPLENCIASEFETIVACOES?,LICENCAS?,PERDASMANDATO?,RENUNCIAS?,ATIVIDADESPARTIDARIAS?,ATIVIDADESPROFISSIONAIS?,ESTUDOSEGRAUSUNIVERSITARIOS?,SEMINARIOS?,ATIVIDADESPARLAMENTARES?,ATIVIDADESSINDICAIS?,CONSELHOS?,CONDECORACOES?,OBRASPUBLICADAS?,MISSOESOFICIAS?,OUTRASINFORMACOES?,FORMATODATANASCIMENTO?)+>
  <!ELEMENT IDECADASTRO (#PCDATA)>
  <!ELEMENT MANDATOSCD (#PCDATA)>
  <!ELEMENT MANDATOSEXTERNOS (#PCDATA)>
  <!ELEMENT NUMGABINETE (#PCDATA)>
  <!ELEMENT ANEXO (#PCDATA)>
  <!ELEMENT ANDAR (#PCDATA)>
  <!ELEMENT TELEFONE (#PCDATA)>
  <!ELEMENT FAX (#PCDATA)>
  <!ELEMENT CODPESSOA (#PCDATA)>
  <!ELEMENT TXTNOMEPARLAMENTAR (#PCDATA)>
  <!ELEMENT TXTNOME (#PCDATA)>
  <!ELEMENT INDSEXO (#PCDATA)>
  <!ELEMENT NUMCARTEIRAPARLAMENTAR (#PCDATA)>
  <!ELEMENT NUMERODAULTIMALEGISLATURA (#PCDATA)>
  <!ELEMENT SIGPARTIDO (#PCDATA)>
  <!ELEMENT SIGUFREPRESENTACAO (#PCDATA)>
  <!ELEMENT DATNASCIMENTO (#PCDATA)>
  <!ELEMENT GRAUINSTRUCAO (#PCDATA)>
  <!ELEMENT NATURALIDADE (#PCDATA)>
  <!ELEMENT PROFISSOES (#PCDATA)>
  <!ELEMENT FILIACAO (#PCDATA)>
  <!ELEMENT CONJUGE (#PCDATA)>
  <!ELEMENT FILHOS (#PCDATA)>
  <!ELEMENT LEGISLATURAS (#PCDATA)>
  <!ELEMENT MANDATOSELETIVOS (#PCDATA)>
  <!ELEMENT FILIACOESPARTIDARIAS (#PCDATA)>
  <!ELEMENT AFASTAMENTOS (#PCDATA)>
  <!ELEMENT SUPLENCIASEFETIVACOES (#PCDATA)>
  <!ELEMENT LICENCAS (#PCDATA)>
  <!ELEMENT PERDASMANDATO (#PCDATA)>
  <!ELEMENT RENUNCIAS (#PCDATA)>
  <!ELEMENT ATIVIDADESPARTIDARIAS (#PCDATA)>
  <!ELEMENT ATIVIDADESPROFISSIONAIS (#PCDATA)>
  <!ELEMENT ESTUDOSEGRAUSUNIVERSITARIOS (#PCDATA)>
  <!ELEMENT SEMINARIOS (#PCDATA)>
  <!ELEMENT ATIVIDADESPARLAMENTARES (#PCDATA)>
  <!ELEMENT ATIVIDADESSINDICAIS (#PCDATA)>
  <!ELEMENT CONSELHOS (#PCDATA)>
  <!ELEMENT CONDECORACOES (#PCDATA)>
  <!ELEMENT OBRASPUBLICADAS (#PCDATA)>
  <!ELEMENT MISSOESOFICIAS (#PCDATA)>
  <!ELEMENT OUTRASINFORMACOES (#PCDATA)>
  <!ELEMENT FORMATODATANASCIMENTO (#PCDATA)>
]>
<main>
  <DATA_RECORD>
    <IDECADASTRO>62881</IDECADASTRO>
    <MANDATOSCD>Deputado Federal, 2011-2015, CE, PMDB. Dt. Posse: 01/02/2011.</MANDATOSCD>
    <NUMGABINETE>384</NUMGABINETE>
    <ANEXO>3</ANEXO>
    <ANDAR>3</ANDAR>
    <TELEFONE>3215-5384</TELEFONE>
    <FAX>3215-2384</FAX>
    <CODPESSOA>189056</CODPESSOA>
    <TXTNOMEPARLAMENTAR>DANILO FORTE</TXTNOMEPARLAMENTAR>
    <TXTNOME>Francisco Danilo Bastos Forte </TXTNOME>
    <INDSEXO>M</INDSEXO>
    <NUMCARTEIRAPARLAMENTAR>95</NUMCARTEIRAPARLAMENTAR>
    <NUMERODAULTIMALEGISLATURA>54</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>PMDB</SIGPARTIDO>
    <SIGUFREPRESENTACAO>CE</SIGUFREPRESENTACAO>
    <DATNASCIMENTO>01/09/58</DATNASCIMENTO>
    <GRAUINSTRUCAO>Superior</GRAUINSTRUCAO>
    <NATURALIDADE>Fortaleza, CE</NATURALIDADE>
    <PROFISSOES>Advogado</PROFISSOES>
    <LEGISLATURAS>2011-2015</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, 2011-2015, CE, PMDB. Dt. Posse: 01/02/2011.</MANDATOSELETIVOS>
    <FILIACOESPARTIDARIAS>PMDB, 1982-2001; PCdoB, 2001-2008; PMDB, 2008-.</FILIACOESPARTIDARIAS>
    <ATIVIDADESPARTIDARIAS>Atividade Partid&#225;ria - C&#226;mara dos Deputados&#10;Vice-L&#237;der, PMDB, 6/2/2013-.&#10;&#10;Atividade Partid&#225;ria - Externas &#224; C&#226;mara dos Deputados&#10;Membro, Diret&#243;rio Nacional e Estadual, PMDB, 2009.</ATIVIDADESPARTIDARIAS>
    <ATIVIDADESPROFISSIONAIS>Diretor Executivo, Funda&#231;&#227;o Nacional de Sa&#250;de &#40;FUNASA&#41;, Bras&#237;lia, DF, 2005-2007; Presidente, Funda&#231;&#227;o Nacional de Sa&#250;de, Bras&#237;lia, DF, 2007-2010;  Assessor Legislativo, Lideran&#231;a do Governo no Congresso Nacional, Bras&#237;lia, DF, 2003-2004;  Assessor Especial, Minist&#233;rio da Articula&#231;&#227;o Pol&#237;tica, Bras&#237;lia, DF, 2003-2004; Presidente, Funda&#231;&#227;o Ulysses Guimar&#227;es do Cear&#225;, Fortaleza, CE, 2010.</ATIVIDADESPROFISSIONAIS>
    <ESTUDOSEGRAUSUNIVERSITARIOS>Direito, Universidade de Fortaleza &#40;UNIFOR&#41;, CE, 1998-2002;  Engenharia Mec&#226;nica, Universidade do Cear&#225; &#40;UFC&#41;, Fortaleza, CE, 1978-1982.</ESTUDOSEGRAUSUNIVERSITARIOS>
    <ATIVIDADESPARLAMENTARES>C&#194;MARA DOS DEPUTADOS - 54&#170; Legislatura&#10;COMISS&#195;O PERMANENTE: Comiss&#227;o de Seguridade Social e Fam&#237;lia - CSSF: Suplente,  1/3/2011 - 31/1/2012; Comiss&#227;o de Constitui&#231;&#227;o e Justi&#231;a e de Cidadania - CCJC: Titular,  1/3/2011 - 31/1/2012; Comiss&#227;o de Seguridade Social e Fam&#237;lia - CSSF: Suplente,  7/3/2012 - 2/2/2013; Comiss&#227;o de Constitui&#231;&#227;o e Justi&#231;a e de Cidadania - CCJC: Titular,  7/3/2012 - 2/2/2013, 5/3/2013 - ; Comiss&#227;o de Seguridade Social e Fam&#237;lia - CSSF: Suplente,  5/3/2013 - .&#10;COMISS&#195;O ESPECIAL: PEC 214/12 - ASSIST&#202;NCIA &#192; SA&#218;DE PARA SERVIDORES: Suplente; PEC 204/12 - INDICA&#199;&#195;O MEMBROS MINIST&#201;RIO P&#218;BLICO: Titular; PLP 251/05 - DESPESA COM PESSOAL NA &#193;REA DA SA&#218;DE: Titular; REFORMA POL&#205;TICA: Suplente,  2/3/2011 - ; PEC 010/95 - SISTEMA DISTRITAL MISTO: Suplente,  26/5/2011 - ; SEGURAN&#199;A P&#218;BLICA: Titular,  28/6/2011 - ; PL 1749/11 - EMPRESA DE SERVI&#199;OS HOSPITALARES: Titular,  17/8/2011 - 15/12/2011; Relator,  23/8/2011 - 15/12/2011; PL 6025/05 - C&#211;DIGO DE PROCESSO CIVIL: Suplente,  25/8/2011 - ; PEC 565/06 - EXECU&#199;&#195;O DA LEI OR&#199;AMENT&#193;RIA ANUAL: Suplente,  23/4/2013 - ; PL 1927/03 - DESONERA&#199;&#195;O TRIBUT&#193;RIA DO TRANSPORTE: Suplente,  11/9/2013 - ; PEC 011/11 - NOMEA&#199;&#195;O PARA FUN&#199;&#195;O DE CONFIAN&#199;A: Titular,  12/9/2013 - .&#10;COMISS&#195;O EXTERNA: TRANSPOSI&#199;&#195;O DO RIO S&#195;O FRANCISCO: Titular; LUTA DOS IND&#205;GENAS: Titular,  1/11/2012 - .&#10;GRUPO DE TRABALHO: GRUPO DE TRABALHO - D&#205;VIDA DOS ESTADOS COM A UNI&#195;O: Titular,  19/3/2012 - 30/5/2012.</ATIVIDADESPARLAMENTARES>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDECADASTRO>62926</IDECADASTRO>
    <MANDATOSCD>Deputado Federal, 2003-2007, RS, PTB. Dt. Posse: 01/02/2003.</MANDATOSCD>
    <MANDATOSEXTERNOS>Vereador, Santo &#194;ngelo/RS, Partido: PDS,&#10;Per&#237;odo: 1989 a 1993</MANDATOSEXTERNOS>
    <CODPESSOA>108567</CODPESSOA>
    <TXTNOMEPARLAMENTAR>PASTOR REINALDO</TXTNOMEPARLAMENTAR>
    <TXTNOME>Reinaldo Santos e Silva</TXTNOME>
    <INDSEXO>M</INDSEXO>
    <NUMCARTEIRAPARLAMENTAR>512</NUMCARTEIRAPARLAMENTAR>
    <NUMERODAULTIMALEGISLATURA>52</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>PTB</SIGPARTIDO>
    <SIGUFREPRESENTACAO>RS</SIGUFREPRESENTACAO>
    <DATNASCIMENTO>14/02/49</DATNASCIMENTO>
    <GRAUINSTRUCAO>Superior Incompleto</GRAUINSTRUCAO>
    <NATURALIDADE>Miracema, RJ</NATURALIDADE>
    <PROFISSOES>Professor, Ministro Evang&#233;lico e T&#233;cnico em Agrimensura</PROFISSOES>
    <FILIACAO>Silvio da Silva e Maria  Jos&#233; dos Santos Silva</FILIACAO>
    <CONJUGE>Marlene Mac&#225;rio e Silva</CONJUGE>
    <FILHOS>Juliana e Silvio</FILHOS>
    <LEGISLATURAS>2003-2007</LEGISLATURAS>
    <MANDATOSELETIVOS>Vereador, 1989-1993, Santo &#194;ngelo, RS, PDS; Deputado Federal, 2003-2007, RS, PTB. Dt. Posse: 01/02/2003.</MANDATOSELETIVOS>
    <FILIACOESPARTIDARIAS>PTB; PDS</FILIACOESPARTIDARIAS>
    <ATIVIDADESPARTIDARIAS>Vice-L&#237;der do PTB, 2003-.</ATIVIDADESPARTIDARIAS>
    <ESTUDOSEGRAUSUNIVERSITARIOS>T&#233;cnico, Escola T&#233;cnica Federal de Santa Catarina, Florian&#243;polis, 1967-1970; Engenharia Civil &#40;incompleto&#41;, FURB, 1975-.</ESTUDOSEGRAUSUNIVERSITARIOS>
    <ATIVIDADESPARLAMENTARES>C&#194;MARA DOS DEPUTADOS:&#10;COMISS&#213;ES PERMANENTES: Agricultura e Pol&#237;tica Rural: Suplente; Ci&#234;ncia e Tecnologia, Comunica&#231;&#227;o e Inform&#225;tica: Suplente, 3/2005-3/2006; Defesa do Consumidor, Meio Ambiente e Minorias: Titular; Direitos Humanos: Titular; Direitos Humanos e Minorias: Titular, 3/2005-3/2006, 3/2006- e Suplente, -3/2005; Legisla&#231;&#227;o Participativa: Titular, 3/2005-3/2006, 3/2006-; Minas e Energia: Suplente, 3/2006-; Seguran&#231;a P&#250;blica e Combate ao Crime Organizado: Suplente, 3/2005-3/2006, 3/2006-; Turismo e Desporto: Primeiro-Vice-Presidente, -3/2005 e Titular, -3/2005. &#10;COMISS&#213;ES ESPECIAIS: PEC n&#186; 215/03, Acumula&#231;&#227;o de Cargos para Militares: Titular, 4/2005-; PEC n&#186; 347/96, Sess&#227;o Legislativa: Suplente-; PEC n&#186; 438/01, Trabalho Escravo: Suplente-; PEC n&#186; 548/02, Coliga&#231;&#245;es Eleitorais: Titular, 5/2005-2/2006; PL n&#186; 3.638/00, Estatuto do Portador de Necessidades Especiais: Titular-; PL n&#186; 4.776/05, Gest&#227;o de Florestas P&#250;blicas: Suplente, 3/2005-; PL n&#186; 5.234/05, Prote&#231;&#227;o Crian&#231;as Amea&#231;adas de Morte: Titular, 5/2006-.&#10;CPI: Biopirataria: Suplente, 8/2004-3/2006.</ATIVIDADESPARLAMENTARES>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDECADASTRO>64224</IDECADASTRO>
    <MANDATOSCD>Deputado Federal, 2003-2007, BA, PFL. Dt. Posse: 01/02/2003.</MANDATOSCD>
    <MANDATOSEXTERNOS>Deputado Estadual, BA, Partido: PFL,&#10;Per&#237;odo: 1991 a 1995&#10;Deputado Estadual, BA, Partido: PFL,&#10;Per&#237;odo: 1995 a 1999&#10;Deputado Estadual, BA, Partido: PFL,&#10;Per&#237;odo: 1999 a 2003</MANDATOSEXTERNOS>
    <CODPESSOA>108632</CODPESSOA>
    <TXTNOMEPARLAMENTAR>ROB&#201;RIO NUNES</TXTNOMEPARLAMENTAR>
    <TXTNOME>Rob&#233;rio C&#225;ssio Ribeiro Nunes</TXTNOME>
    <INDSEXO>M</INDSEXO>
    <NUMCARTEIRAPARLAMENTAR>213</NUMCARTEIRAPARLAMENTAR>
    <NUMERODAULTIMALEGISLATURA>52</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>PFL</SIGPARTIDO>
    <SIGUFREPRESENTACAO>BA</SIGUFREPRESENTACAO>
    <DATNASCIMENTO>03/11/64</DATNASCIMENTO>
    <GRAUINSTRUCAO>Superior</GRAUINSTRUCAO>
    <NATURALIDADE>Maca&#250;bas, BA</NATURALIDADE>
    <PROFISSOES>Advogado</PROFISSOES>
    <FILIACAO>Sebasti&#227;o Nunes e Selma Lisete de Castro Ribeiro Nunes</FILIACAO>
    <CONJUGE>Fl&#225;via Nayda Magalh&#227;es Nunes</CONJUGE>
    <FILHOS>Felipe, Rob&#233;rio e Roger Magalh&#227;es Ribeiro Nunes</FILHOS>
    <LEGISLATURAS>2003-2007</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Estadual, 1991-1995, BA, PFL; Deputado Estadual, 1995-1999, BA, PFL; Deputado Estadual, 1999-2003, BA, PFL; Deputado Federal, 2003-2007, BA, PFL. Dt. Posse: 01/02/2003.</MANDATOSELETIVOS>
    <FILIACOESPARTIDARIAS>PFL, 1986-.</FILIACOESPARTIDARIAS>
    <ATIVIDADESPROFISSIONAIS>Office-Boy, Banco do Brasil, Maca&#250;bas, BA, 1979-1983; Assessor Parlamentar, C&#226;mara dos Deputados, Salvador, BA, 1985-1986 e 1987-1991.</ATIVIDADESPROFISSIONAIS>
    <ESTUDOSEGRAUSUNIVERSITARIOS>Direito, UCSAL, Salvador, BA, 1986-1992.</ESTUDOSEGRAUSUNIVERSITARIOS>
    <ATIVIDADESPARLAMENTARES>C&#194;MARAS MUNICIPAIS, ASSEMBL&#201;IAS LEGISLATIVAS E C&#194;MARA LEGISLATIVA DO DF: ALBA: Mesa: Terceiro-Secret&#225;rio e Terceiro-Vice-Presidente; Comiss&#227;o de Defesa ao Consumidor: Vice-Presidente e Titular; Comiss&#227;o de Desenvolvimento Econ&#244;mico e Turismo: Titular; Comiss&#227;o de Direitos Humanos: Suplente; Comiss&#227;o de Fiscaliza&#231;&#227;o e Controle: Presidente; Comiss&#227;o de Minas, Energia, Ci&#234;ncia e Tecnologia: Titular; Comiss&#227;o de Prote&#231;&#227;o ao Meio Ambiente: Titular; Comiss&#227;o Especial de Combate &#224; Fome: Titular; Comiss&#227;o Especial de Defesa dos Direitos da Mulher: Titular; Comiss&#227;o Especial de Divis&#227;o Territorial: Titular e Suplente; Comiss&#227;o Especial de Divis&#227;o Territorial: Titular; Comiss&#227;o Especial para Apurar Incidentes no Plen&#225;rio: Titular; Comiss&#227;o Especial sobre C&#243;digo de &#201;tica e Decoro Parlamentar: Presidente; CPI sobre a Venda Irregular de Terras em Porto Seguro: Suplente; CPI sobre o Programa INTERLUZ: Suplente.&#10;C&#194;MARA DOS DEPUTADOS:&#10;COMISS&#213;ES PERMANENTES: Defesa do Consumidor: Titular, 5/2005-3/2006, 3/2006-; Minas e Energia: Titular, 3/2005-5/2005 e Suplente, 3/2004-3/2005; Rela&#231;&#245;es Exteriores e de Defesa Nacional: Suplente, 3/2005-3/2006; Via&#231;&#227;o e Transportes: Suplente, 3/2006-.&#10;COMISS&#213;ES ESPECIAIS: ALCA - &#193;rea de Livre Com&#233;rcio das Am&#233;ricas: Suplente-; PEC n&#186; 101/03, Reelei&#231;&#227;o da Mesa: Titular-; PEC n&#186; 358/05, Reforma do Judici&#225;rio: Titular, 11/2005-; PEC n&#186; 548/02, Coliga&#231;&#245;es Eleitorais: Titular, 5/2005-2/2006; Proposi&#231;&#245;es Referentes a Assuntos da SERASA: Suplente, 05/2005-; Reforma do Judici&#225;rio: Suplente-; PEC n&#186; 007/03,  Agentes Comunit&#225;rios de Sa&#250;de: Titular, 6/2005-.&#10;COMISS&#213;ES EXTERNAS: Enriquecimento de Ur&#226;nio: Titular-.&#10;CPI: Setor de Combust&#237;veis: Suplente.</ATIVIDADESPARLAMENTARES>
    <CONDECORACOES>T&#237;tulos: de Cidad&#227;o, Prefeituras de Paramirim, e S&#227;o Jos&#233; da Vit&#243;ria, BA, 1995; Amigo da PM, Salvador, BA, 1996; Excel&#234;ncia, Universidade de Arad, Rom&#234;nia, 2001.</CONDECORACOES>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDECADASTRO>64960</IDECADASTRO>
    <MANDATOSCD>Deputada Federal, 2003-2007, RR, PST. Dt. Posse: 01/02/2003; Deputada Federal, 2007-2011, RR, PSB. Dt. Posse: 01/02/2007.</MANDATOSCD>
    <CODPESSOA>108903</CODPESSOA>
    <TXTNOMEPARLAMENTAR>MARIA HELENA</TXTNOMEPARLAMENTAR>
    <TXTNOME>Maria Helena Veronese Rodrigues</TXTNOME>
    <INDSEXO>F</INDSEXO>
    <NUMCARTEIRAPARLAMENTAR>5</NUMCARTEIRAPARLAMENTAR>
    <NUMERODAULTIMALEGISLATURA>53</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>PSB</SIGPARTIDO>
    <SIGUFREPRESENTACAO>RR</SIGUFREPRESENTACAO>
    <DATNASCIMENTO>15/06/49</DATNASCIMENTO>
    <GRAUINSTRUCAO>Superior</GRAUINSTRUCAO>
    <NATURALIDADE>Santo &#194;ngelo, RS</NATURALIDADE>
    <PROFISSOES>Advogada e Professora</PROFISSOES>
    <FILIACAO>Dirceu Rodrigues e Ilda Veronese Rodrigues</FILIACAO>
    <CONJUGE>Ariosto Murilo dos Santos</CONJUGE>
    <LEGISLATURAS>2003-2007 e 2007-2011.</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputada Federal, 2003-2007, RR, PST. Dt. Posse: 01/02/2003; Deputada Federal, 2007-2011, RR, PSB. Dt. Posse: 01/02/2007.</MANDATOSELETIVOS>
    <FILIACOESPARTIDARIAS>PSDB, 1995-1999; PST, 1999-2003; PMDB, 2003; PPS, 2003-2005; PSB, 2005-.</FILIACOESPARTIDARIAS>
    <ATIVIDADESPARTIDARIAS>Vice-L&#237;der do PPS, 2004-2005;  Vice-Presidente do Diret&#243;rio Regional do PSB, Roraima, 2005-;  Vice-Presidente do Diret&#243;rio Regional do PSB, RR, 2005-2007;  Presidente do Diret&#243;rio Municipal, Boa Vista, 2007-2009;  Vice-Presidente do Diret&#243;rio Regional, PSB, RR, 2010.</ATIVIDADESPARTIDARIAS>
    <ATIVIDADESPROFISSIONAIS>Chefe de Gabinete, 1974-1976, e Procuradora-Geral, 1976-1979, Prefeitura Municipal, Boa Vista, RR; Chefe do Servi&#231;o de Articula&#231;&#227;o com Munic&#237;pios, 1980-1984, Coordenadora Coopera&#231;&#227;o Externa, 1984-1985, e Diretora de  Planejamento da Secretaria de Sa&#250;de, 1989-1992, Governo Roraima, Boa Vista, RR; Secret&#225;ria  Parlamentar, C&#226;mara dos Deputados, Bras&#237;lia, DF, 1993-2000; Secret&#225;ria de Trabalho e Desenvolvimento Social, Prefeitura Municipal, Boa Vista, RR, 2001-2002.</ATIVIDADESPROFISSIONAIS>
    <ESTUDOSEGRAUSUNIVERSITARIOS>Direito, UFSM, Santa Maria, RS, 1967-1971; Belas Artes &#40;incompleto&#41;, UFSM, Santa Maria, RS, 1968-.</ESTUDOSEGRAUSUNIVERSITARIOS>
    <SEMINARIOS>Tese, Congresso Brasileiro de Procuradores Municipais, Prefeitura Municipal de Porto Alegre, RS, 1982; Palestrante, I Encontro Internacional de Mulheres Socialistas, Bras&#237;lia, DF, 2010.</SEMINARIOS>
    <ATIVIDADESPARLAMENTARES>C&#194;MARA DOS DEPUTADOS - Legislaturas anteriores &#224; 54&#170;&#10;PROCURADORIA ESPECIAL DA MULHER: Procuradora-Adjunta, 2009-.&#10;COMISS&#213;ES PERMANENTES: Amaz&#244;nia e de Desenvolvimento Regional: Titular; Amaz&#244;nia, Integra&#231;&#227;o Nacional e de Desenvolvimento Regional: Presidente, 3/2005-3/2006, 1&#170;  Vice-Presidente, 26/3/2008-4/3/2009, 3&#170;  Vice-Presidente, 3/2006-1/2007, Titular, 3/2005-3/2006, 3/2006-1/2007, 14/2/2007-6/2/2008, 4/3/2008-2/2/2009, 4/3/2009-1/2/2010, 3/3/2010-, e Suplente, -3/2005; Desenvolvimento Urbano: Titular, -3/2005; Seguridade Social e Fam&#237;lia: Titular; Trabalho, Administra&#231;&#227;o e Servi&#231;o P&#250;blico: Suplente, 3/2006-1/2007, 14/2/2007-6/2/2008, 4/3/2008-2/2/2009, 4/3/2009-1/2/2010, 3/3/2010-.&#10;COMISS&#213;ES ESPECIAIS: Ano da Mulher - 2004: Titular; PEC n&#186; 30/07, Licen&#231;a Maternidade: Titular, 13/8/2009-; PEC n&#186; 58/03, Aliena&#231;&#227;o de Terras: Titular; PEC n&#186; 200/03, Servidores de Rond&#244;nia: Titular, 6/2005-1/2007; PEC n&#186; 213/07, Servidores Federais e Ex-Territ&#243;rios: Titular, 15/4/2010-; PEC n&#186; 300/08, Remunera&#231;&#227;o dos Policiais Militares: Titular, 6/8/2009-; PEC n&#186; 483/05, Quadro de Servidores de Rond&#244;nia: Titular, 9/7/2007-11/11/2009; PEC n&#186; 485/05, Juizados Especiais Quest&#227;o Mulheres: Suplente, 15/9/2009-; PEC n&#186; 488/05, Funcion&#225;rios do Extinto Banco de RR: Suplente, 17/8/2009-; PEC n&#186; 544/02, Tribunais Federais Regionais: Suplente; PL n&#186; 1.394/03, Programa do Primeiro Emprego: Suplente; PL n&#186; 1.399/03, Estatuto da Mulher: Titular-; PL n&#186; 1.610/96, Explora&#231;&#227;o Recursos Terras Ind&#237;genas: Titular, 5/11/2007-; PL n&#186; 3.638/00, Estatuto do Portador de Necessidades Especiais: Titular; PL n&#186; 6.493/09, Organiza&#231;&#227;o da Pol&#237;cia Federal: Suplente, 6/4/2010-; PL n&#186; 7.200/06, Reforma Universit&#225;ria: Suplente, 7/2006-1/2007; Reforma Trabalhista: Titular.&#10;COMISS&#213;ES EXTERNAS: Feminiza&#231;&#227;o da Pobreza no Brasil: Titular-; CEXSERRA, Comiss&#227;o Externa Desocupa&#231;&#227;o Raposa Serra do Sol: Titular, 16/4/2009-. &#10;CPIs: Biopirataria: Titular, 3/2005-3/2006, e Suplente, 8/2004-3/2005; ENTARES: Grupo de Trabalho Estatuto da Crian&#231;a e Adolescente: Titular-.&#10;FRENTES PARLAMENTARES: em Defesa dos Direitos da Crian&#231;a e do Adolescente ; Em Defesa dos Povos Ind&#237;genas; em Defesa dos Direitos dos Servidores e Policiais Militares dos Ex-Territ&#243;rios Federais do Acre, Amap&#225;, Roraima e Rond&#244;nia e do Antigo Distrito Federal; em Defesa do Planejamento Familiar: Membro; em Defesa dos Direitos da Crian&#231;a e do Adolescente: Membro; em Defesa dos Direitos dos Povos Ind&#237;genas: Membro; em Defesa em HIV/AIDS: Membro; em Prol do Programa Ant&#225;rtico Brasileiro: Membro.&#10;GRUPOS DE TRABALHO: Grupo Parlamentar Mata Atl&#226;ntica II: Titular.</ATIVIDADESPARLAMENTARES>
    <ATIVIDADESSINDICAIS>Membro, Junta Comercial de Roraima, Boa Vista, RR, 1977-1982; Conselheira Federal, OAB, Boa Vista, RR, 1993-1995.</ATIVIDADESSINDICAIS>
    <CONSELHOS>Membro, Conselho Imobili&#225;rio Territorial de Roraima, Boa Vista, RR, 1981-1983.</CONSELHOS>
    <CONDECORACOES>T&#237;tulo de Cidad&#227; Boavistense; Medalha do M&#233;rito Naval, Bras&#237;lia, DF, 2008; Medalha do M&#233;rito Militar, RR, 2010; Medalha do M&#233;rito Comercial da Federa&#231;&#227;o do Com&#233;rcio de Roraima, FECOR, 2010; Medalha do M&#233;rito Militar e Corpo de Bombeiros de Roraima, RR, 2009; Ordem do M&#233;rito Bombeiro Militar do Distrito Federal, Imperador Dom Pedro II, Brasilia, DF, 2010; Medalha de Honra ao M&#233;rito Santos Dumont concedida pela Aeron&#225;utica Brasileira, Brasilia, DF, 2010.</CONDECORACOES>
    <MISSOESOFICIAS>Como Vice-Presidente da da Frente Parlamentar de apoio ao programa Ant&#225;rtico Brasileiro visitou a Base Brasileira na Ant&#225;rtida Comandante Ferraz, a convite do Comando da Marinha, Ant&#225;rtida, 2005; Chefe da Delega&#231;&#227;o Brasileira que participou do Encontro sobre Planejamento e Ordenamento Territoriais, Planejamento Regional e Urban&#237;stico, Berlim, Alemanha, 2006.Representante da C&#226;mara dos Deputados: na Reuni&#227;o da Comiss&#227;o de Meio Ambiente e Turismo - Parlatino, Oranjestad, Aruba, 2004; na Reuni&#227;o de </MISSOESOFICIAS>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDECADASTRO>65459</IDECADASTRO>
    <MANDATOSCD>Deputado Federal, 1983-1987, CE, PMDB. Dt. Posse: 01/02/1983; Deputado Federal &#40;Constituinte&#41;, 1987-1991, CE, PMDB. Dt. Posse: 01/02/1987; Deputado Federal, 1994-1995, CE, PMDB. Dt. Posse: 19/04/1994.</MANDATOSCD>
    <CODPESSOA>105730</CODPESSOA>
    <TXTNOMEPARLAMENTAR>MANUEL VIANA</TXTNOMEPARLAMENTAR>
    <TXTNOME>Manuel Francisco Viana Neto</TXTNOME>
    <INDSEXO>M</INDSEXO>
    <NUMERODAULTIMALEGISLATURA>49</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>PMDB</SIGPARTIDO>
    <SIGUFREPRESENTACAO>CE</SIGUFREPRESENTACAO>
    <DATNASCIMENTO>03/06/52</DATNASCIMENTO>
    <GRAUINSTRUCAO>Superior</GRAUINSTRUCAO>
    <NATURALIDADE>Fortaleza, CE</NATURALIDADE>
    <PROFISSOES>M&#233;dico</PROFISSOES>
    <FILIACAO>Francisco de Assis Parente Viana e Maria Jos&#233; Melo Viana&#10;</FILIACAO>
    <CONJUGE>Beatriz Irene de Albuquerque Viana&#10;</CONJUGE>
    <LEGISLATURAS>1983-1987, 1987-1991 e 1991-1995.</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, 1983-1987, CE, PMDB. Dt. Posse: 01/02/1983; Deputado Federal &#40;Constituinte&#41;, 1987-1991, CE, PMDB. Dt. Posse: 01/02/1987; Deputado Federal, 1994-1995, CE, PMDB. Dt. Posse: 19/04/1994.</MANDATOSELETIVOS>
    <FILIACOESPARTIDARIAS>MDB, 1974-; PMDB, 1980-.</FILIACOESPARTIDARIAS>
    <SUPLENCIASEFETIVACOES>Assumiu e foi efetivado no mandato de Deputado Federal, na Legislatura 1991-1995, em 18 de abril de 1994, em virtude da perda de mandato do Deputado Carlos Benevides.</SUPLENCIASEFETIVACOES>
    <LICENCAS>Licenciou-se do mandato de Deputado Federal, na legislatura 1983-1987, para tratamento de sa&#250;de por 120 dias, a partir de 17 de maio de 1983, reassumindo em 14 de setembro de 1983; por 150 dias a partir de 7 de mar&#231;o de 1984, reassumindo em 4 de agosto de 1984; Licenciou-se do mandato de Deputado Federal na legislatura 1987-1991, para tratamento de sa&#250;de, por 122 dias, a partir de 12 de dezembro de 1988, prorrogada por mais 120 dias, a partir de 13 de abril de 1989, e prorrogada por 60 dias at&#233; 1</LICENCAS>
    <ATIVIDADESPROFISSIONAIS>Chefe, Setor de Negrologia, S.A. Socorros M&#233;dicos &#40;SOS&#41; e Instituto Jos&#233; Frota, Fortaleza, CE; Diretor-Presidente, Ana Nery Hospitalar Ltda.; Diretor-Cl&#237;nico, Cl&#237;nica Miguel Couto; M&#233;dico, INAMPS; M&#233;dico, Prefeitura Municipal de Fortaleza, CE.</ATIVIDADESPROFISSIONAIS>
    <ESTUDOSEGRAUSUNIVERSITARIOS>Medicina, UFC, Fortaleza, CE, 1975 &#40;conclus&#227;o&#41;.</ESTUDOSEGRAUSUNIVERSITARIOS>
    <ATIVIDADESPARLAMENTARES>ASSEMBL&#201;IA NACIONAL CONSTITUINTE:&#10;COMISS&#213;ES: Subcomiss&#227;o da Nacionalidade, da Soberania e das Rela&#231;&#245;es Internacionais, da Comiss&#227;o da Soberania e dos Direitos e Garantias do Homem e da Mulher: Titular, 1987; Comiss&#227;o de Sistematiza&#231;&#227;o: Suplente, 1987-1988.&#10;C&#194;MARA DOS DEPUTADOS:&#10;COMISS&#213;ES: de Sa&#250;de: Titular, 1983.</ATIVIDADESPARLAMENTARES>
    <OUTRASINFORMACOES>Chefe do Setor de Nefrologia do S.A. Socorros M&#233;dicos &#40;sos&#41; e do Instituto Jos&#233; Frota, Fortaleza, CE. M&#233;dico do Inamps e da Prefeitura Municipal de Fortaleza. Diretor-cl&#237;nico da Cl&#237;nica Miguel Couto. Diretor-Presidente da Ana Nery Hospitalar Ltda. Eleito Suplente de Deputado Federal para a legislatura 1991-1995, Tomou posse e foi efetivado em 18 de abril de 1994.&#10;&#10;Endere&#231;o eletr&#244;nico para contato: eliomarmaia2&#64;gmail.com</OUTRASINFORMACOES>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDECADASTRO>65468</IDECADASTRO>
    <MANDATOSCD>Deputado Federal &#40;Constituinte&#41;, 1987-1991, PR, PMDB. Dt. Posse: 01/02/1987; Deputado Federal, 1993-1995, PR, PTB. Dt. Posse: 20/12/1993.</MANDATOSCD>
    <MANDATOSEXTERNOS>Deputado Estadual, PR, Partido: PMDB,&#10;Per&#237;odo: 1983 a 1987</MANDATOSEXTERNOS>
    <CODPESSOA>106474</CODPESSOA>
    <TXTNOMEPARLAMENTAR>ERVIN BONKOSKI</TXTNOMEPARLAMENTAR>
    <TXTNOME>Ervin Bonkoski</TXTNOME>
    <INDSEXO>M</INDSEXO>
    <NUMCARTEIRAPARLAMENTAR>589</NUMCARTEIRAPARLAMENTAR>
    <NUMERODAULTIMALEGISLATURA>49</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>PTB</SIGPARTIDO>
    <SIGUFREPRESENTACAO>PR</SIGUFREPRESENTACAO>
    <DATNASCIMENTO>26/09/36</DATNASCIMENTO>
    <GRAUINSTRUCAO>Superior</GRAUINSTRUCAO>
    <NATURALIDADE>Perdizes, SC</NATURALIDADE>
    <PROFISSOES>Advogado e Radialista</PROFISSOES>
    <FILIACAO>Estefano Bonkoski&#10; e Tecla Bonkoski</FILIACAO>
    <CONJUGE>Maria do Roccio Cobbe Bonkoski&#10;</CONJUGE>
    <LEGISLATURAS>1987-1991 e 1991-1995.</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Estadual, 1983-1987, PR, PMDB; Deputado Federal &#40;Constituinte&#41;, 1987-1991, PR, PMDB. Dt. Posse: 01/02/1987; Deputado Federal, 1993-1995, PR, PTB. Dt. Posse: 20/12/1993.</MANDATOSELETIVOS>
    <FILIACOESPARTIDARIAS>ARENA, 1978-1979; PMDB, 1981-1987; PTB, 1988-.</FILIACOESPARTIDARIAS>
    <SUPLENCIASEFETIVACOES>Assumiu, como Suplente, o mandato de Deputado Federal para a legislatura 1991-1995, sendo Efetivado em 20 de dezembro de 1993.</SUPLENCIASEFETIVACOES>
    <LICENCAS>Licenciou-se do mandato de Deputado Federal, na Legislatura 1987-1991, para Tratamento de Sa&#250;de, de 19 a 24 de maio, de 26 de maio a 12 de junho, e de 01 a 06 de agosto, de 1988;&#10;Licenciou-se do mandato de Deputado Federal, na Legislatura 1987-1991, para Tratamento de Sa&#250;de, de 24 de julho a 20 de agosto de 1989;&#10;Licenciou-se do mandato de Deputado Federal, na Legislatura 1987-1991, para Tratamento de Sa&#250;de, pelo per&#237;odo de 30 &#40;trinta&#41; dias, a partir de 25 de outubro de 1990;&#10;Licenciou-se do mand</LICENCAS>
    <ATIVIDADESPROFISSIONAIS>Diretor-Superintendente, R&#225;dio Colombo do Paran&#225; e R&#225;dio Musical FM de Campo Mour&#227;o, PR.</ATIVIDADESPROFISSIONAIS>
    <ESTUDOSEGRAUSUNIVERSITARIOS>Direito, UFPR, Curitiba, 1956-1960; &#10;Jornalismo, PUC, Curitiba, PR, 1961; &#10;Ci&#234;ncias Cont&#225;beis e Atuariais, Fac. Ci&#234;ncias Econ&#244;micas, Curitiba, PR, 1965-1968.</ESTUDOSEGRAUSUNIVERSITARIOS>
    <ATIVIDADESPARLAMENTARES>C&#194;MARAS MUNICIPAIS, ASSEMBL&#201;IAS LEGISLATIVAS E C&#194;MARA LEGISLATIVA DO DF: &#10;ALPR: Comiss&#227;o de Constitui&#231;&#227;o e Justi&#231;a: Titular, 1983-1984 e Suplente, 1985; Comiss&#227;o de Cultura e Esporte: Titular, 1986 e Suplente, 1985-1986; Comiss&#227;o de Defesa do Consumidor: Titular, 1985-1986; Comiss&#227;o de Finan&#231;as: Presidente, 1983-1985; Comiss&#227;o de Ind&#250;stria e Com&#233;rcio: Titular, 1984; Comiss&#227;o de Obras P&#250;blicas, Transportes e Comunica&#231;&#227;o: Titular, 1983 e Suplente, 1984-1986; Comiss&#227;o de Recursos Humanos: Titular, 1985 e Suplente, 1984; Comiss&#227;o de Tomada de Contas: Titular, 1983; Comiss&#227;o de Turismo: Titular, 1983-1985; &#10;&#10;ASSEMBL&#201;IA NACIONAL CONSTITUINTE: &#10;Comiss&#227;o da Ci&#234;ncia e Tecnologia: Titular, 1987; Comiss&#227;o da Comunica&#231;&#227;o: Titular, 1987; Comiss&#227;o da Educa&#231;&#227;o, Cultura e Esportes: Titular, 1987; Comiss&#227;o da Fam&#237;lia: Titular, 1987; Comiss&#227;o da Organiza&#231;&#227;o Eleitoral, Partid&#225;ria e Garantia das Institui&#231;&#245;es: Suplente, 1987; Subcomiss&#227;o da Fam&#237;lia, do Menor e do Idoso: Titular, 1987; Subcomiss&#227;o do Sistema Eleitoral e Partidos Pol&#237;ticos: Suplente, 1987.&#10;&#10;C&#194;MARA DOS DEPUTADOS:&#10;COMISS&#213;ES PERMANENTES: Constitui&#231;&#227;o e Justi&#231;a e de Reda&#231;&#227;o: Suplente, 1994; Economia, Ind&#250;stria e Com&#233;rcio: Titular, 1994.&#10;&#10;COMISS&#212;ES ESPECIAIS: Legalidade do Jogo: Suplente, 1994.</ATIVIDADESPARLAMENTARES>
    <CONDECORACOES>Cidad&#227;o Honor&#225;rio de Curitiba, PR, C&#226;mara Municipal, 1983; Cidad&#227;o Honor&#225;rio de Tijucas do Sul, PR, C&#226;mara Municipal, 1986.</CONDECORACOES>
    <OBRASPUBLICADAS>Manual de M&#250;sica Funcional</OBRASPUBLICADAS>
    <MISSOESOFICIAS>Membro da Delega&#231;&#227;o da C&#226;mara dos Deputados, &#224; 78&#170; Confer&#234;ncia Interparlamentar, Bangkok, Tail&#226;ndia, 12 a 17/10/1987;</MISSOESOFICIAS>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDECADASTRO>65472</IDECADASTRO>
    <MANDATOSCD>Deputado Federal &#40;Constituinte&#41;, 1987-1991, RJ, PTB. Dt. Posse: 01/02/1987; Deputado Federal, 1991-1994, RJ, PTB. Dt. Posse: 01/02/1991.</MANDATOSCD>
    <CODPESSOA>104097</CODPESSOA>
    <TXTNOMEPARLAMENTAR>F&#193;BIO RAUNHEITTI</TXTNOMEPARLAMENTAR>
    <TXTNOME>F&#225;bio Raunheitti</TXTNOME>
    <INDSEXO>M</INDSEXO>
    <NUMERODAULTIMALEGISLATURA>49</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>PTB</SIGPARTIDO>
    <SIGUFREPRESENTACAO>RJ</SIGUFREPRESENTACAO>
    <DATNASCIMENTO>11/09/28</DATNASCIMENTO>
    <GRAUINSTRUCAO>Superior</GRAUINSTRUCAO>
    <NATURALIDADE>Nova Igua&#231;u, RJ</NATURALIDADE>
    <PROFISSOES>Advogado, Tabeli&#227;o e Professor de Direito</PROFISSOES>
    <FILIACAO>Jos&#233; Raunheitti&#10; e Dulcec&#237;lia de Moura Raunheitti&#10;</FILIACAO>
    <CONJUGE>L&#237;dia Gon&#231;alves Raunheitti&#10;</CONJUGE>
    <LEGISLATURAS>1987-1991 e 1991-1995.</LEGISLATURAS>