<?xml version="1.0" ?>
<!DOCTYPE main [
  <!ELEMENT main (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (IDECADASTRO?,MANDATOSCD?,MANDATOSEXTERNOS?,NUMGABINETE?,ANEXO?,ANDAR?,TELEFONE?,FAX?,CODPESSOA?,TXTNOMEPARLAMENTAR?,TXTNOME?,INDSEXO?,NUMCARTEIRAPARLAMENTAR?,NUMERODAULTIMALEGISLATURA?,SIGPARTIDO?,SIGUFREPRESENTACAO?,DATNASCIMENTO?,GRAUINSTRUCAO?,NATURALIDADE?,PROFISSOES?,FILIACAO?,CONJUGE?,FILHOS?,LEGISLATURAS?,MANDATOSELETIVOS?,FILIACOESPARTIDARIAS?,AFASTAMENTOS?,SUPLENCIASEFETIVACOES?,LICENCAS?,PERDASMANDATO?,RENUNCIAS?,ATIVIDADESPARTIDARIAS?,ATIVIDADESPROFISSIONAIS?,ESTUDOSEGRAUSUNIVERSITARIOS?,SEMINARIOS?,ATIVIDADESPARLAMENTARES?,ATIVIDADESSINDICAIS?,CONSELHOS?,CONDECORACOES?,OBRASPUBLICADAS?,MISSOESOFICIAS?,OUTRASINFORMACOES?,FORMATODATANASCIMENTO?)+>
  <!ELEMENT IDECADASTRO (#PCDATA)>
  <!ELEMENT MANDATOSCD (#PCDATA)>
  <!ELEMENT MANDATOSEXTERNOS (#PCDATA)>
  <!ELEMENT NUMGABINETE (#PCDATA)>
  <!ELEMENT ANEXO (#PCDATA)>
  <!ELEMENT ANDAR (#PCDATA)>
  <!ELEMENT TELEFONE (#PCDATA)>
  <!ELEMENT FAX (#PCDATA)>
  <!ELEMENT CODPESSOA (#PCDATA)>
  <!ELEMENT TXTNOMEPARLAMENTAR (#PCDATA)>
  <!ELEMENT TXTNOME (#PCDATA)>
  <!ELEMENT INDSEXO (#PCDATA)>
  <!ELEMENT NUMCARTEIRAPARLAMENTAR (#PCDATA)>
  <!ELEMENT NUMERODAULTIMALEGISLATURA (#PCDATA)>
  <!ELEMENT SIGPARTIDO (#PCDATA)>
  <!ELEMENT SIGUFREPRESENTACAO (#PCDATA)>
  <!ELEMENT DATNASCIMENTO (#PCDATA)>
  <!ELEMENT GRAUINSTRUCAO (#PCDATA)>
  <!ELEMENT NATURALIDADE (#PCDATA)>
  <!ELEMENT PROFISSOES (#PCDATA)>
  <!ELEMENT FILIACAO (#PCDATA)>
  <!ELEMENT CONJUGE (#PCDATA)>
  <!ELEMENT FILHOS (#PCDATA)>
  <!ELEMENT LEGISLATURAS (#PCDATA)>
  <!ELEMENT MANDATOSELETIVOS (#PCDATA)>
  <!ELEMENT FILIACOESPARTIDARIAS (#PCDATA)>
  <!ELEMENT AFASTAMENTOS (#PCDATA)>
  <!ELEMENT SUPLENCIASEFETIVACOES (#PCDATA)>
  <!ELEMENT LICENCAS (#PCDATA)>
  <!ELEMENT PERDASMANDATO (#PCDATA)>
  <!ELEMENT RENUNCIAS (#PCDATA)>
  <!ELEMENT ATIVIDADESPARTIDARIAS (#PCDATA)>
  <!ELEMENT ATIVIDADESPROFISSIONAIS (#PCDATA)>
  <!ELEMENT ESTUDOSEGRAUSUNIVERSITARIOS (#PCDATA)>
  <!ELEMENT SEMINARIOS (#PCDATA)>
  <!ELEMENT ATIVIDADESPARLAMENTARES (#PCDATA)>
  <!ELEMENT ATIVIDADESSINDICAIS (#PCDATA)>
  <!ELEMENT CONSELHOS (#PCDATA)>
  <!ELEMENT CONDECORACOES (#PCDATA)>
  <!ELEMENT OBRASPUBLICADAS (#PCDATA)>
  <!ELEMENT MISSOESOFICIAS (#PCDATA)>
  <!ELEMENT OUTRASINFORMACOES (#PCDATA)>
  <!ELEMENT FORMATODATANASCIMENTO (#PCDATA)>
]>
<main>
  <DATA_RECORD>
    <IDECADASTRO>701</IDECADASTRO>
    <MANDATOSCD>Deputado Federal, 1860, ES, ; Deputado Federal, 1861-1863, ES, . Dt. Posse: 03/05/1861.</MANDATOSCD>
    <MANDATOSEXTERNOS>Deputado Provincial, SP, Partido: N/D,&#10;Per&#237;odo:  a &#10;Governador, SC, Partido: N/D,&#10;Per&#237;odo:  a &#10;Governador, RN, Partido: N/D,&#10;Per&#237;odo:  a &#10;Governador, ES, Partido: N/D,&#10;Per&#237;odo:  a </MANDATOSEXTERNOS>
    <CODPESSOA>118071</CODPESSOA>
    <TXTNOMEPARLAMENTAR>PEREIRA PINTO</TXTNOMEPARLAMENTAR>
    <TXTNOME>Antonio Pereira Pinto</TXTNOME>
    <INDSEXO>M</INDSEXO>
    <NUMERODAULTIMALEGISLATURA>11</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>SEM PARTIDO</SIGPARTIDO>
    <SIGUFREPRESENTACAO>ES</SIGUFREPRESENTACAO>
    <DATNASCIMENTO>20/03/19</DATNASCIMENTO>
    <GRAUINSTRUCAO>Superior</GRAUINSTRUCAO>
    <NATURALIDADE>Rio de Janeiro, RJ</NATURALIDADE>
    <PROFISSOES>Bacharel  em Direito e Magistrado</PROFISSOES>
    <LEGISLATURAS>1857-1860 e 1861-1863.</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Provincial, , SP, ; Governador, , ES, ; Governador, , RN, ; Governador, , SC, ; Deputado Federal, -1860, ES, ; Deputado Federal, 1861-1863, ES, . Dt. Posse: 03/05/1861.</MANDATOSELETIVOS>
    <ATIVIDADESPROFISSIONAIS>Entrando para a classe da Magistratura, exerceu o cargo de Promotor P&#250;blico da capital de S&#227;o Paulo; Serviu o cargo de Pagador da Tesouraria de Marinha; Depois foi Juiz de &#211;rf&#227;os de Campos; Foi tamb&#233;m Oficial da Secretaria da Justi&#231;a; Mais tarde, Juiz de Direito, em Guaratinguet&#225;; Por fim, foi Diretor da Secretaria da C&#226;mara dos Deputados, em cujo exerc&#237;cio faleceu.</ATIVIDADESPROFISSIONAIS>
    <ESTUDOSEGRAUSUNIVERSITARIOS>Formado em Direito na Faculdade de S&#227;o Paulo.</ESTUDOSEGRAUSUNIVERSITARIOS>
    <ATIVIDADESPARLAMENTARES>CD:&#10;MESA: 1&#186; Secret&#225;rio, 1860-1863; 2&#186; Secret&#225;rio, 1858-1859; 3&#186; Secret&#225;rio, 1857.</ATIVIDADESPARLAMENTARES>
    <ATIVIDADESSINDICAIS>S&#243;cio do Instituto Hist&#243;rico e Geogr&#225;fico Brasileiro.</ATIVIDADESSINDICAIS>
    <CONSELHOS>Membro do Conselho de sua magestade o Imperador.</CONSELHOS>
    <CONDECORACOES>Mo&#231;o Fidalgo da Casa Imperial; Comendador da Ordem da Rosa; Cavaleiro da Ordem de Cristo.</CONDECORACOES>
    <OBRASPUBLICADAS>Apontamentos para o direito internacional ou cole&#231;&#227;o completa dos tratados celebrados pelo Brasil com diferentes na&#231;&#245;es estrangeiras, acompanhada de uma not&#237;cia hist&#243;rica e documentada sobre as conve&#231;&#245;es mais importantes, Rio de Janeiro, 1864-1868, 4 vols; Estudos sobre algumas quest&#245;es internacionais, Rio de Janeiro, 1867; Pol&#237;tica internacional - Interven&#231;&#227;o do Brasil no Rio da Prata, Rio de Janeiro, 1871; Reforma eleitoral - Projetos oferecidos &#224; considera&#231;&#227;o do corpo legislativo desde 1826 at&#233; 1874, seguidos de documentos hist&#243;ricos, explicativos acera da promulga&#231;&#227;o do ato adicional, etc. Rio de Janeiro, 1874; Falas do trono de 1826 a 1872, acompanhadas dos respectivos todos de gra&#231;a da C&#226;mara Tempor&#225;ria, Rio de Janeiro, 1872; Anais do parlamento, compilados, etc. Rio de Janeiro - publicou Pereira Pinto os volumes correspondentes a 1823, 1826 a 1832, 1834, 1847 a 1856 inclusive, deixando preparado o material para a publica&#231;&#227;o subsequente; Relat&#243;rio e sinopse dos trabalhos da C&#226;mara dos Deputados - de 1869 a 1879, trabalho que foi continuado por seu sucessor, o Dr. Jorge Jo&#227;o Dodsworth.&#10;H&#225; na Revista do Instituto diversos trabalhos deste autor, como: Elogio hist&#243;rico de Antonio Carlos Ribeiro de Andrada; Mem&#243;ria acerca do sistema penitenci&#225;rio no Brasil; A confedera&#231;&#227;o do Equador, not&#237;cia hist&#243;rica sobre a revolu&#231;&#227;o de Pernambuco de 1824; Limites do Brasil, 1493 a 1851, 1867.</OBRASPUBLICADAS>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDECADASTRO>702</IDECADASTRO>
    <MANDATOSCD>Deputado Federal, 1860, GO, .</MANDATOSCD>
    <CODPESSOA>118072</CODPESSOA>
    <TXTNOMEPARLAMENTAR>CUNHA MATTOS</TXTNOMEPARLAMENTAR>
    <TXTNOME>Lib&#226;nio Augusto da Cunha Mattos</TXTNOME>
    <INDSEXO>M</INDSEXO>
    <NUMERODAULTIMALEGISLATURA>10</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>SEM PARTIDO</SIGPARTIDO>
    <SIGUFREPRESENTACAO>GO</SIGUFREPRESENTACAO>
    <DATNASCIMENTO>02/10/18</DATNASCIMENTO>
    <NATURALIDADE>N&#227;o informado, PE</NATURALIDADE>
    <PROFISSOES>Funcion&#225;rio P&#250;blico</PROFISSOES>
    <FILIACAO>Raymundo da Cunha Mattos</FILIACAO>
    <LEGISLATURAS>1857-1860</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, -1860, GO, .</MANDATOSELETIVOS>
    <ATIVIDADESPROFISSIONAIS>Diretor Geral da 1&#170; diretoria da Secretaria da Guerra; Muito jovem, entrou para esta secretaria e subira do lugar de Amanuense sucessivamente at&#233; este, em que faleceu.</ATIVIDADESPROFISSIONAIS>
    <ATIVIDADESSINDICAIS>S&#243;cio do Instituto Hist&#243;rico e Geogr&#225;fico Brasileiro e da Sociedade Auxiliadora da Ind&#250;stria Nacional.</ATIVIDADESSINDICAIS>
    <CONDECORACOES>Oficial da Ordem da Rosa.</CONDECORACOES>
    <OBRASPUBLICADAS>Breve &#237;ndice alfab&#233;tico da legisla&#231;&#227;o brasileira, cujo conhecimento mais interessa aos empregados da reparti&#231;&#227;o da guerra, compreendendo as disposi&#231;&#245;es impressas desde 1837 at&#233; 1860, Rio de Janeiro, 1864.</OBRASPUBLICADAS>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDECADASTRO>703</IDECADASTRO>
    <MANDATOSCD>Deputado Federal, 1857-1860, GO, . Dt. Posse: 26/05/1857; Deputado Federal, 1861-1863, GO, . Dt. Posse: 04/06/1861.</MANDATOSCD>
    <CODPESSOA>118074</CODPESSOA>
    <TXTNOMEPARLAMENTAR>SANTA CRUZ</TXTNOMEPARLAMENTAR>
    <TXTNOME>Felippe Antonio Cardoso de Santa Cruz</TXTNOME>
    <INDSEXO>M</INDSEXO>
    <NUMERODAULTIMALEGISLATURA>11</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>SEM PARTIDO</SIGPARTIDO>
    <SIGUFREPRESENTACAO>GO</SIGUFREPRESENTACAO>
    <NATURALIDADE>, </NATURALIDADE>
    <LEGISLATURAS>1857-1860 e 1861-1863.</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, 1857-1860, GO, . Dt. Posse: 26/05/1857; Deputado Federal, 1861-1863, GO, . Dt. Posse: 04/06/1861.</MANDATOSELETIVOS>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDECADASTRO>704</IDECADASTRO>
    <MANDATOSCD>Deputado Federal, 1857-1860, MA, . Dt. Posse: 11/05/1857.</MANDATOSCD>
    <CODPESSOA>118075</CODPESSOA>
    <TXTNOMEPARLAMENTAR>BAR&#195;O DE S&#195;O BENTO</TXTNOMEPARLAMENTAR>
    <TXTNOME>Francisco Mariano de Viveiros Sobrinho</TXTNOME>
    <INDSEXO>M</INDSEXO>
    <NUMERODAULTIMALEGISLATURA>10</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>SEM PARTIDO</SIGPARTIDO>
    <SIGUFREPRESENTACAO>MA</SIGUFREPRESENTACAO>
    <DATNASCIMENTO>12/01/19</DATNASCIMENTO>
    <NATURALIDADE>Alc&#226;ntara, MA</NATURALIDADE>
    <PROFISSOES>Bacharel em Direito</PROFISSOES>
    <LEGISLATURAS>1857-1860</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, 1857-1860, MA, . Dt. Posse: 11/05/1857.</MANDATOSELETIVOS>
    <CONDECORACOES>Fidalgo Cavaleiro da Casa Imperial.</CONDECORACOES>
    <OBRASPUBLICADAS>A elei&#231;&#227;o do 2&#186; distrito eleitoral da prov&#237;ncia do Maranh&#227;o, Rio de Janeiro, 1857;</OBRASPUBLICADAS>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDECADASTRO>705</IDECADASTRO>
    <MANDATOSCD>Deputado Federal, 1860, MA, .</MANDATOSCD>
    <CODPESSOA>118076</CODPESSOA>
    <TXTNOMEPARLAMENTAR>BELFORT</TXTNOMEPARLAMENTAR>
    <TXTNOME>Jos&#233; Joaquim Teixeira Vieira Belfort</TXTNOME>
    <INDSEXO>M</INDSEXO>
    <NUMERODAULTIMALEGISLATURA>10</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>SEM PARTIDO</SIGPARTIDO>
    <SIGUFREPRESENTACAO>MA</SIGUFREPRESENTACAO>
    <NATURALIDADE>, </NATURALIDADE>
    <LEGISLATURAS>1857-1860</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, -1860, MA, .</MANDATOSELETIVOS>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDECADASTRO>706</IDECADASTRO>
    <MANDATOSCD>Deputado Federal, 1860, MA, ; Deputado Federal, 1861-1863, MA, . Dt. Posse: 03/05/1861.</MANDATOSCD>
    <CODPESSOA>118078</CODPESSOA>
    <TXTNOMEPARLAMENTAR>DIAS VIEIRA</TXTNOMEPARLAMENTAR>
    <TXTNOME>Jo&#227;o Pedro Dias Vieira</TXTNOME>
    <INDSEXO>M</INDSEXO>
    <NUMERODAULTIMALEGISLATURA>11</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>SEM PARTIDO</SIGPARTIDO>
    <SIGUFREPRESENTACAO>MA</SIGUFREPRESENTACAO>
    <NATURALIDADE>, </NATURALIDADE>
    <LEGISLATURAS>1857-1860 e 1861-1863.</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, -1860, MA, ; Deputado Federal, 1861-1863, MA, . Dt. Posse: 03/05/1861.</MANDATOSELETIVOS>
    <ATIVIDADESPARLAMENTARES>CD:&#10;MESA: Vice-Presidente, 1857.</ATIVIDADESPARLAMENTARES>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDECADASTRO>707</IDECADASTRO>
    <MANDATOSCD>Deputado Federal, 1857-1860, MA, . Dt. Posse: 19/05/1857; Deputado Federal, 1861-1863, MA, . Dt. Posse: 03/05/1861; Deputado Federal, 1866, MA, .</MANDATOSCD>
    <CODPESSOA>118079</CODPESSOA>
    <TXTNOMEPARLAMENTAR>GOMES DE SOUZA</TXTNOMEPARLAMENTAR>
    <TXTNOME>Joaquim Gomes de Souza</TXTNOME>
    <INDSEXO>M</INDSEXO>
    <NUMERODAULTIMALEGISLATURA>12</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>SEM PARTIDO</SIGPARTIDO>
    <SIGUFREPRESENTACAO>MA</SIGUFREPRESENTACAO>
    <DATNASCIMENTO>15/02/29</DATNASCIMENTO>
    <GRAUINSTRUCAO>Superior</GRAUINSTRUCAO>
    <NATURALIDADE>Itapicur&#250;, MA</NATURALIDADE>
    <PROFISSOES>M&#233;dico, Professor e Doutor em Matem&#225;tica</PROFISSOES>
    <FILIACAO>Ignacio Jos&#233; de Souza e Antonia Carneiro de Brito Souza</FILIACAO>
    <LEGISLATURAS>1857-1860, 1861-1863 e 1864-1866.</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, 1857-1860, MA, . Dt. Posse: 19/05/1857; Deputado Federal, 1861-1863, MA, . Dt. Posse: 03/05/1861; Deputado Federal, -1866, MA, .</MANDATOSELETIVOS>
    <ATIVIDADESPROFISSIONAIS>Foi nomeado Lente susbstituto e mais tarde Lente catedr&#225;tico da Academia Militar, depois Escola Central.</ATIVIDADESPROFISSIONAIS>
    <ESTUDOSEGRAUSUNIVERSITARIOS>Tendo assentado pra&#231;a no ex&#233;rcito para satisfazer a vontade de seus pais, estudou 1 ano na </ESTUDOSEGRAUSUNIVERSITARIOS>
    <ATIVIDADESSINDICAIS>S&#243;cio das Academias de Londres, Berlim e Vienna d&#39;&#193;ustria.</ATIVIDADESSINDICAIS>
    <OBRASPUBLICADAS>Disserta&#231;&#227;o sobre o modo de indagar novos astros sem aux&#237;lio das observa&#231;&#245;es diretas, Rio de Janeiro, 1858; Resolu&#231;&#227;o das equa&#231;&#245;es num&#233;ricas - vem no Guanabara, tomo 1&#186;, 1850; M&#233;todos gerais de integra&#231;&#227;o e da integral da equa&#231;&#227;o diferencial do problema do som - no Guanabara, tomo 2&#186;; Recueil de memoires d&#39;analyse et physique mathematiques, Leipzig, 1857, contendo as seguintes mem&#243;rias: Mem&#243;ria sobre a teoria do som; Mem&#243;ria sobre a propaga&#231;&#227;o dos movimentos nos meios el&#225;sticos, compreendendo o movimento nos meios cristal&#243;ides, e teoria da luz; Mem&#243;ria sobre as vibra&#231;&#245;es nos meios el&#225;sticos; Mem&#243;ria sobre as resolu&#231;&#245;es alg&#233;bricas ou transcendentes por integrais definidas; Mem&#243;ria sobre esp&#233;cies de c&#225;lculos novos, compreedendo toda teoria dos caracter&#237;sticos e sobre os principios fundamentais da an&#225;lise geral; Fisiologia geral das ci&#234;ncias matem&#225;ticas e uniformiza&#231;&#227;o dos m&#233;todos anal&#237;ticos; Mem&#243;ria sobre o c&#225;lculo dos res&#237;duos; Mem&#243;ria sobre a aplica&#231;&#227;o da an&#225;lise &#224; f&#237;sica matem&#225;tica com aplica&#231;&#245;es a muitas quest&#245;es gerais. Melanges de c&#225;lculo integral, Leipzig, 1882; Leis da natureza, ou c&#243;digo de legisla&#231;&#227;o em que, passando em revista o universo, pretende expor as leis fixas, gerais e inveri&#225;veis que presidiram a sua organiza&#231;&#227;o; Anthologie universelle: choix des meilleurs poesies lyriques de diverses nations dans les langues originales, Leipzig, 1859.</OBRASPUBLICADAS>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDECADASTRO>708</IDECADASTRO>
    <MANDATOSCD>Deputado Federal, 1859-1860, MA, . Dt. Posse: 18/05/1859; Deputado Federal, 1869-1872, SP, . Dt. Posse: 11/05/1869; Deputado Federal, 1875, SP, ; Deputado Federal, 1877-1877, SP, . Dt. Posse: 01/02/1877.</MANDATOSCD>
    <CODPESSOA>118080</CODPESSOA>
    <TXTNOMEPARLAMENTAR>JO&#195;O MENDES</TXTNOMEPARLAMENTAR>
    <TXTNOME>Jo&#227;o Mendes de Almeida 1&#186;</TXTNOME>
    <INDSEXO>M</INDSEXO>
    <NUMERODAULTIMALEGISLATURA>16</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>SEM PARTIDO</SIGPARTIDO>
    <SIGUFREPRESENTACAO>SP</SIGUFREPRESENTACAO>
    <DATNASCIMENTO>22/05/31</DATNASCIMENTO>
    <GRAUINSTRUCAO>Superior</GRAUINSTRUCAO>
    <NATURALIDADE>Caxias, MA</NATURALIDADE>
    <PROFISSOES>Advogado</PROFISSOES>
    <FILIACAO>Fernando Mendes de Almeida e Esmeria Alves de Souza</FILIACAO>
    <FILHOS>Jo&#227;o Mendes de Almeida 2&#186;</FILHOS>
    <LEGISLATURAS>1857-1860, 1869-1872, 1872-1875 e 1876-1877.</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, 1859-1860, MA, . Dt. Posse: 18/05/1859; Deputado Federal, 1869-1872, SP, . Dt. Posse: 11/05/1869; Deputado Federal, -1875, SP, ; Deputado Federal, 1877-1877, SP, . Dt. Posse: 01/02/1877.</MANDATOSELETIVOS>
    <ATIVIDADESPROFISSIONAIS>Antes de dar-se &#224; Advocacia, foi Juiz municipal e de &#243;rf&#227;os, em Jundia&#237;; Exerceu a Advocacia em S&#227;o Paulo.</ATIVIDADESPROFISSIONAIS>
    <ESTUDOSEGRAUSUNIVERSITARIOS>Estudou em Pernambuco os quatro primeiros anos de curso jur&#237;dico; Bacharel em Ci&#234;ncias Soci</ESTUDOSEGRAUSUNIVERSITARIOS>
    <ATIVIDADESPARLAMENTARES>C&#194;MARA DOS DEPUTADOS:&#10;COMISS&#213;ES ESPECIAIS: Comiss&#227;o para examinar o projeto apresentado pelo Senado acerca da liberta&#231;&#227;o do ventre escravo: Membro.</ATIVIDADESPARLAMENTARES>
    <ATIVIDADESSINDICAIS>Membro do Instituto Hist&#243;rico e Geogr&#225;fico Brasileiro; Membro e Presidente da Sociedade dos Homens de Letra</ATIVIDADESSINDICAIS>
    <OBRASPUBLICADAS>A c&#226;mara quatrienal e a agricultura, S&#227;o Paulo, 1857; Breves considera&#231;&#245;es hist&#243;rico-pol&#237;ticas sobre a discuss&#227;o do elemento servil na C&#226;mara dos Deputados, Rio de Janeiro, 1871; O Senado e a reforma constitucional: ligeiras considera&#231;&#245;es por um deputado &#224; Assembl&#233;ia Geral Legislativa, Rio de Janeiro, 1879; Manifesto ao partido conservador em S&#227;o Paulo, S&#227;o Paulo, 1882; Quest&#245;es sociais - A escravid&#227;o, S&#227;o Paulo, 1883; Quest&#245;es forenses, S&#227;o Paulo, 1878-1892, 4 vols; Algumas notas geneal&#243;gicasa - Livro de fam&#237;lia, Portugal, Espanha, Flandres-Brebante, Brasil, S&#227;o Paulo, Maranh&#227;o, S&#233;culos XVI-XIX, S&#227;o Paulo, 1886; A Capitania de S&#227;o Vicente de Paulo, sua origem - Legenda hist&#243;rica, S&#227;o Paulo, 1887; Dicion&#225;rio Geogr&#225;fico da prov&#237;ncia de S&#227;o Paulo.&#10;O Dr. Jo&#227;o Mendes foi correspondente do Jonarl do Com&#233;rcio do Rio de Janeiro, colaborou no Di&#225;rio de S&#227;o Paulo e na Ordem, &#243;rg&#227;o do clero paulistano, e redigiu: A Lei - jornal especialmente pol&#237;tico, S&#227;o Paulo, 1857-1858 - continuou esta publica&#231;&#227;o at&#233; 1861; Opini&#227;o Conservadora - folha pol&#237;tica e cat&#243;lica, S&#227;o Paulo, 1869-1872; A Sentinella - &#243;rg&#227;o pol&#237;tico e cat&#243;lico, S&#227;o Paulo, 1876-1879.</OBRASPUBLICADAS>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDECADASTRO>709</IDECADASTRO>
    <MANDATOSCD>Deputado Federal, 1858-1860, MA, . Dt. Posse: 26/04/1858.</MANDATOSCD>
    <CODPESSOA>118081</CODPESSOA>
    <TXTNOMEPARLAMENTAR>JO&#195;O PAULO</TXTNOMEPARLAMENTAR>
    <TXTNOME>Jo&#227;o Paulo de Miranda</TXTNOME>
    <INDSEXO>M</INDSEXO>
    <NUMERODAULTIMALEGISLATURA>10</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>SEM PARTIDO</SIGPARTIDO>
    <SIGUFREPRESENTACAO>MA</SIGUFREPRESENTACAO>
    <NATURALIDADE>, </NATURALIDADE>
    <PROFISSOES>Magistrado</PROFISSOES>
    <LEGISLATURAS>1857-1860</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, 1858-1860, MA, . Dt. Posse: 26/04/1858.</MANDATOSELETIVOS>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDECADASTRO>710</IDECADASTRO>
    <MANDATOSCD>Deputado Federal, 1858-1860, MA, . Dt. Posse: 30/04/1858.</MANDATOSCD>
    <CODPESSOA>118082</CODPESSOA>
    <TXTNOMEPARLAMENTAR>RODRIGUES LOPES</TXTNOMEPARLAMENTAR>
    <TXTNOME>Jos&#233; Joaquim Rodrigues Lopes</TXTNOME>
    <INDSEXO>M</INDSEXO>
    <NUMERODAULTIMALEGISLATURA>10</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>SEM PARTIDO</SIGPARTIDO>
    <SIGUFREPRESENTACAO>MA</SIGUFREPRESENTACAO>
    <DATNASCIMENTO>13/01/03</DATNASCIMENTO>
    <GRAUINSTRUCAO>Superior</GRAUINSTRUCAO>
    <NATURALIDADE>N&#227;o informado, MA</NATURALIDADE>
    <PROFISSOES>Marechal de Campo e Militar do Ex&#233;rcito</PROFISSOES>
    <FILIACAO>Jos&#233; Joaquim Rodrigues Lopes e Brigida Rosa Lopes</FILIACAO>
    <LEGISLATURAS>1857-1860</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, 1858-1860, MA, . Dt. Posse: 30/04/1858.</MANDATOSELETIVOS>
    <ATIVIDADESPROFISSIONAIS>Entrou para o Corpo de Engenheiros, como 2&#186; Tenente, em 1827; Exerceu o cargo de Secret&#225;rio do Conselho Supremo Militar, hoje Supremo Tribunal Militar, 1859-1895; Foi reformado no posto de Marechal de Campo.</ATIVIDADESPROFISSIONAIS>
    <ESTUDOSEGRAUSUNIVERSITARIOS>Formado no curso de Matem&#225;ticas Militares da Academia de Marinha de Lisboa e no de Qu&#237;mica.</ESTUDOSEGRAUSUNIVERSITARIOS>
    <ATIVIDADESSINDICAIS>S&#243;cio da Sociedade Liter&#225;ria do Rio de Janeiro.</ATIVIDADESSINDICAIS>
    <CONDECORACOES>Bar&#227;o de Mattoso por Portugal; Foi agraciado com o t&#237;tulo de Conselho do Imperador; Fidalgo Cavaleiro da Casa Imperial e da Casa Real portuguesa; Cavaleiro da Ordem de S&#227;o Bento d</CONDECORACOES>
    <OBRASPUBLICADAS>Documentos sobre a pir&#226;mide do Campo Ourique do Maranh&#227;o, planeada pelo major, etc. Maranh&#227;o, 1849; Plani-hist&#243;ria ou resumo sin&#243;tico-hist&#243;rico-geneal&#243;gico do imp&#233;rio do Brasil e do reino de Portugal e das fam&#237;lias reinantes nestes pa&#237;ses, oferecido a SS. MM. os senhores D. Pedro II, Imperador do Brasil e D. Pedro V, Rei de Portugal, Pernambuco, 1858; Carta geral da prov&#237;ncia do Maranh&#227;o, correta e aumentada, desenhada e oferecida &#224; Sociedade Liter&#225;ria do Rio de Janeiro por seu s&#243;cio efetivo Jos&#233; Joaquim Rodrigues Lopes, e mandada gravar pela mesma sociedade, em 1841, sob a dire&#231;&#227;o de Antonio P. F. M. Antas, etc. Rio de Janeiro; Mapa de uma parte da prov&#237;ncia do Maranh&#227;o para servir na quest&#227;o entre as comarcas de Caxias, Brejo e Itapicur&#250;-mirim, levantado em 1847; Mapa topogr&#225;fico da parte da rep&#250;blica do Paraguai que tem sido ocupada pelos ex&#233;rcitos aliados, constru&#237;do por ordem do Exm&#186; Sr. Marqu&#234;s de Caxias, Marechal do ex&#233;rcito e General em chefe dos mesmos ex&#233;rcitos, mediante os trabalhos dos membros da comiss&#227;o de engenheiros dos tr&#234;s corpos do ex&#233;rcito brasileiro, reduzido, coordenado e desenhado sob a dire&#231;&#227;o do coronel-engenheiro Jos&#233; Joaquim Rodrigues Lopes, pelo dito capit&#227;o A. Vilella de C. Tavares, em agosto de 1868.</OBRASPUBLICADAS>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDECADASTRO>711</IDECADASTRO>
    <MANDATOSCD>Deputado Federal, 1860, MT, .</MANDATOSCD>
    <CODPESSOA>118084</CODPESSOA>
    <TXTNOMEPARLAMENTAR>DELFINO DE ALMEIDA</TXTNOMEPARLAMENTAR>
    <TXTNOME>Jos&#233; Delphino de Almeida</TXTNOME>
    <INDSEXO>M</INDSEXO>
    <NUMERODAULTIMALEGISLATURA>10</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>SEM PARTIDO</SIGPARTIDO>
    <SIGUFREPRESENTACAO>MT</SIGUFREPRESENTACAO>
    <NATURALIDADE>, </NATURALIDADE>
    <PROFISSOES>Negociante</PROFISSOES>
    <LEGISLATURAS>1857-1860</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, -1860, MT, .</MANDATOSELETIVOS>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDECADASTRO>712</IDECADASTRO>
    <MANDATOSCD>Deputado Federal, 1860, MT, .</MANDATOSCD>
    <CODPESSOA>118085</CODPESSOA>
    <TXTNOMEPARLAMENTAR>PEIXOTO DE AZEVEDO</TXTNOMEPARLAMENTAR>
    <TXTNOME>Antonio Peixoto de Azevedo</TXTNOME>
    <INDSEXO>M</INDSEXO>
    <NUMERODAULTIMALEGISLATURA>10</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>SEM PARTIDO</SIGPARTIDO>
    <SIGUFREPRESENTACAO>MT</SIGUFREPRESENTACAO>
    <NATURALIDADE>, </NATURALIDADE>
    <PROFISSOES>Militar</PROFISSOES>
    <LEGISLATURAS>1857-1860</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, -1860, MT, .</MANDATOSELETIVOS>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDECADASTRO>713</IDECADASTRO>
    <MANDATOSCD>Deputado Federal, 1857-1860, MT, . Dt. Posse: 10/05/1857; Deputado Federal, 1861-1863, MT, . Dt. Posse: 11/05/1861.</MANDATOSCD>
    <CODPESSOA>118086</CODPESSOA>
    <TXTNOMEPARLAMENTAR>COUTO</TXTNOMEPARLAMENTAR>
    <TXTNOME>Antonio Corr&#234;a do Couto</TXTNOME>
    <INDSEXO>M</INDSEXO>
    <NUMERODAULTIMALEGISLATURA>11</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>SEM PARTIDO</SIGPARTIDO>
    <SIGUFREPRESENTACAO>MT</SIGUFREPRESENTACAO>
    <GRAUINSTRUCAO>Superior</GRAUINSTRUCAO>
    <NATURALIDADE>Cuiab&#225;, MT</NATURALIDADE>
    <LEGISLATURAS>1857-1860 e 1861-1863.</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, 1857-1860, MT, . Dt. Posse: 10/05/1857; Deputado Federal, 1861-1863, MT, . Dt. Posse: 11/05/1861.</MANDATOSELETIVOS>
    <ESTUDOSEGRAUSUNIVERSITARIOS>Bacharel em Ci&#234;ncias Sociais e Jur&#237;dicas pela Faculdade de S&#227;o Paulo.</ESTUDOSEGRAUSUNIVERSITARIOS>
    <OBRASPUBLICADAS>Disserta&#231;&#227;o sobre o atual governo da rep&#250;blica do Paraguai, seguida da descri&#231;&#227;o de Coimbra, do P&#227;o de A&#231;&#250;car, e de outros lugares; dos atos de vandalismo praticados no Mato Grosso por sua ordem; da contesta&#231;&#227;o ao pretendido direito &#224; parte do territ&#243;rio da dita prov&#237;ncia, e da indica&#231;&#227;o dos meios de se lhe fazer a guerra em desafronta das atrocidades e insultos cometidos pelos seus odiciais e soldados, Rio de Janeiro, 1865.</OBRASPUBLICADAS>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDECADASTRO>714</IDECADASTRO>
    <MANDATOSCD>Deputado Federal, 1860, MG, .</MANDATOSCD>
    <CODPESSOA>118087</CODPESSOA>
    <TXTNOMEPARLAMENTAR>ALC&#194;NTARA MACHADO</TXTNOMEPARLAMENTAR>
    <TXTNOME>Pedro de Alc&#226;ntara Machado</TXTNOME>
    <INDSEXO>M</INDSEXO>
    <NUMERODAULTIMALEGISLATURA>10</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>SEM PARTIDO</SIGPARTIDO>
    <SIGUFREPRESENTACAO>MG</SIGUFREPRESENTACAO>
    <NATURALIDADE>, </NATURALIDADE>
    <PROFISSOES>Negociante</PROFISSOES>
    <LEGISLATURAS>1857-1860</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, -1860, MG, .</MANDATOSELETIVOS>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDECADASTRO>715</IDECADASTRO>
    <MANDATOSCD>Deputado Federal, 1857-1860, MG, . Dt. Posse: 11/05/1857.</MANDATOSCD>
    <CODPESSOA>118088</CODPESSOA>
    <TXTNOMEPARLAMENTAR>ATA&#205;DE</TXTNOMEPARLAMENTAR>
    <TXTNOME>Francisco de Assis Athayde</TXTNOME>
    <INDSEXO>M</INDSEXO>
    <NUMERODAULTIMALEGISLATURA>10</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>SEM PARTIDO</SIGPARTIDO>
    <SIGUFREPRESENTACAO>MG</SIGUFREPRESENTACAO>
    <NATURALIDADE>, </NATURALIDADE>
    <PROFISSOES>Coronel</PROFISSOES>
    <LEGISLATURAS>1857-1860</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, 1857-1860, MG, . Dt. Posse: 11/05/1857.</MANDATOSELETIVOS>
    <ATIVIDADESPARLAMENTARES>CD:&#10;MESA: 2&#186; Suplente, 1857.</ATIVIDADESPARLAMENTARES>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDECADASTRO>716</IDECADASTRO>
    <MANDATOSCD>Deputado Federal, 1857-1860, MG, . Dt. Posse: 18/05/1857; Deputado Federal, 1862-1863, MG, . Dt. Posse: 12/05/1862; Deputado Federal, 1864-1866, MG, . Dt. Posse: 15/02/1864.</MANDATOSCD>
    <CODPESSOA>118093</CODPESSOA>
    <TXTNOMEPARLAMENTAR>CESAR</TXTNOMEPARLAMENTAR>
    <TXTNOME>Antonio Joaquim Cesar</TXTNOME>
    <INDSEXO>M</INDSEXO>
    <NUMERODAULTIMALEGISLATURA>12</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>SEM PARTIDO</SIGPARTIDO>
    <SIGUFREPRESENTACAO>MG</SIGUFREPRESENTACAO>
    <NATURALIDADE>, </NATURALIDADE>
    <PROFISSOES>Advogado</PROFISSOES>
    <LEGISLATURAS>1857-1860, 1861-1863 e 1864-1866.</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, 1857-1860, MG, . Dt. Posse: 18/05/1857; Deputado Federal, 1862-1863, MG, . Dt. Posse: 12/05/1862; Deputado Federal, 1864-1866, MG, . Dt. Posse: 15/02/1864.</MANDATOSELETIVOS>
    <ATIVIDADESPARLAMENTARES>CD:&#10;MESA: 4&#186; Secret&#225;rio, 1866.</ATIVIDADESPARLAMENTARES>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDECADASTRO>717</IDECADASTRO>
    <MANDATOSCD>Deputado Federal, 1860, MG, .</MANDATOSCD>
    <CODPESSOA>118094</CODPESSOA>
    <TXTNOMEPARLAMENTAR>CYRILLO</TXTNOMEPARLAMENTAR>
    <TXTNOME>Francisco Ciryllo Ribeiro e Souza</TXTNOME>
    <INDSEXO>M</INDSEXO>
    <NUMERODAULTIMALEGISLATURA>10</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>SEM PARTIDO</SIGPARTIDO>
    <SIGUFREPRESENTACAO>MG</SIGUFREPRESENTACAO>
    <NATURALIDADE>, </NATURALIDADE>
    <PROFISSOES>M&#233;dico</PROFISSOES>
    <LEGISLATURAS>1857-1860</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, -1860, MG, .</MANDATOSELETIVOS>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDECADASTRO>718</IDECADASTRO>
    <MANDATOSCD>Deputado Federal, 1858-1860, MG, . Dt. Posse: 01/05/1858.</MANDATOSCD>
    <CODPESSOA>118095</CODPESSOA>
    <TXTNOMEPARLAMENTAR>CHAGAS ANDRADE</TXTNOMEPARLAMENTAR>
    <TXTNOME>Jo&#227;o das Chagas Andrade</TXTNOME>
    <INDSEXO>M</INDSEXO>
    <NUMERODAULTIMALEGISLATURA>10</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>SEM PARTIDO</SIGPARTIDO>
    <SIGUFREPRESENTACAO>MG</SIGUFREPRESENTACAO>
    <NATURALIDADE>, </NATURALIDADE>
    <PROFISSOES>Doutor</PROFISSOES>
    <LEGISLATURAS>1857-1860</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, 1858-1860, MG, . Dt. Posse: 01/05/1858.</MANDATOSELETIVOS>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDECADASTRO>719</IDECADASTRO>
    <MANDATOSCD>Deputado Federal, 1860, MG, .</MANDATOSCD>
    <CODPESSOA>118098</CODPESSOA>
    <TXTNOMEPARLAMENTAR>FELIPPE DE ARA&#218;JO</TXTNOMEPARLAMENTAR>
    <TXTNOME>Antonio Felippe de Ara&#250;jo</TXTNOME>
    <INDSEXO>M</INDSEXO>