<?xml version="1.0" ?>
<!DOCTYPE main [
  <!ELEMENT main (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (IDECADASTRO?,MANDATOSCD?,MANDATOSEXTERNOS?,NUMGABINETE?,ANEXO?,ANDAR?,TELEFONE?,FAX?,CODPESSOA?,TXTNOMEPARLAMENTAR?,TXTNOME?,INDSEXO?,NUMCARTEIRAPARLAMENTAR?,NUMERODAULTIMALEGISLATURA?,SIGPARTIDO?,SIGUFREPRESENTACAO?,DATNASCIMENTO?,GRAUINSTRUCAO?,NATURALIDADE?,PROFISSOES?,FILIACAO?,CONJUGE?,FILHOS?,LEGISLATURAS?,MANDATOSELETIVOS?,FILIACOESPARTIDARIAS?,AFASTAMENTOS?,SUPLENCIASEFETIVACOES?,LICENCAS?,PERDASMANDATO?,RENUNCIAS?,ATIVIDADESPARTIDARIAS?,ATIVIDADESPROFISSIONAIS?,ESTUDOSEGRAUSUNIVERSITARIOS?,SEMINARIOS?,ATIVIDADESPARLAMENTARES?,ATIVIDADESSINDICAIS?,CONSELHOS?,CONDECORACOES?,OBRASPUBLICADAS?,MISSOESOFICIAS?,OUTRASINFORMACOES?,FORMATODATANASCIMENTO?)+>
  <!ELEMENT IDECADASTRO (#PCDATA)>
  <!ELEMENT MANDATOSCD (#PCDATA)>
  <!ELEMENT MANDATOSEXTERNOS (#PCDATA)>
  <!ELEMENT NUMGABINETE (#PCDATA)>
  <!ELEMENT ANEXO (#PCDATA)>
  <!ELEMENT ANDAR (#PCDATA)>
  <!ELEMENT TELEFONE (#PCDATA)>
  <!ELEMENT FAX (#PCDATA)>
  <!ELEMENT CODPESSOA (#PCDATA)>
  <!ELEMENT TXTNOMEPARLAMENTAR (#PCDATA)>
  <!ELEMENT TXTNOME (#PCDATA)>
  <!ELEMENT INDSEXO (#PCDATA)>
  <!ELEMENT NUMCARTEIRAPARLAMENTAR (#PCDATA)>
  <!ELEMENT NUMERODAULTIMALEGISLATURA (#PCDATA)>
  <!ELEMENT SIGPARTIDO (#PCDATA)>
  <!ELEMENT SIGUFREPRESENTACAO (#PCDATA)>
  <!ELEMENT DATNASCIMENTO (#PCDATA)>
  <!ELEMENT GRAUINSTRUCAO (#PCDATA)>
  <!ELEMENT NATURALIDADE (#PCDATA)>
  <!ELEMENT PROFISSOES (#PCDATA)>
  <!ELEMENT FILIACAO (#PCDATA)>
  <!ELEMENT CONJUGE (#PCDATA)>
  <!ELEMENT FILHOS (#PCDATA)>
  <!ELEMENT LEGISLATURAS (#PCDATA)>
  <!ELEMENT MANDATOSELETIVOS (#PCDATA)>
  <!ELEMENT FILIACOESPARTIDARIAS (#PCDATA)>
  <!ELEMENT AFASTAMENTOS (#PCDATA)>
  <!ELEMENT SUPLENCIASEFETIVACOES (#PCDATA)>
  <!ELEMENT LICENCAS (#PCDATA)>
  <!ELEMENT PERDASMANDATO (#PCDATA)>
  <!ELEMENT RENUNCIAS (#PCDATA)>
  <!ELEMENT ATIVIDADESPARTIDARIAS (#PCDATA)>
  <!ELEMENT ATIVIDADESPROFISSIONAIS (#PCDATA)>
  <!ELEMENT ESTUDOSEGRAUSUNIVERSITARIOS (#PCDATA)>
  <!ELEMENT SEMINARIOS (#PCDATA)>
  <!ELEMENT ATIVIDADESPARLAMENTARES (#PCDATA)>
  <!ELEMENT ATIVIDADESSINDICAIS (#PCDATA)>
  <!ELEMENT CONSELHOS (#PCDATA)>
  <!ELEMENT CONDECORACOES (#PCDATA)>
  <!ELEMENT OBRASPUBLICADAS (#PCDATA)>
  <!ELEMENT MISSOESOFICIAS (#PCDATA)>
  <!ELEMENT OUTRASINFORMACOES (#PCDATA)>
  <!ELEMENT FORMATODATANASCIMENTO (#PCDATA)>
]>
<main>
  <DATA_RECORD>
    <IDECADASTRO>1802</IDECADASTRO>
    <MANDATOSCD>Deputado Federal &#40;Constituinte&#41;, 1890-1893, SE, . Dt. Posse: 15/11/1890; Deputado Federal, 1903-1905, SE, . Dt. Posse: 06/05/1903; Deputado Federal, 1906-1909, SE, . Dt. Posse: 08/05/1906.</MANDATOSCD>
    <CODPESSOA>119629</CODPESSOA>
    <TXTNOMEPARLAMENTAR>OLIVEIRA VALAD&#195;O</TXTNOMEPARLAMENTAR>
    <TXTNOME>Manoel Prisciliano de Oliveira Valad&#227;o</TXTNOME>
    <INDSEXO>M</INDSEXO>
    <NUMERODAULTIMALEGISLATURA>27</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>SEM PARTIDO</SIGPARTIDO>
    <SIGUFREPRESENTACAO>SE</SIGUFREPRESENTACAO>
    <DATNASCIMENTO>04/01/49</DATNASCIMENTO>
    <NATURALIDADE>, </NATURALIDADE>
    <PROFISSOES>Militar</PROFISSOES>
    <LEGISLATURAS>1891-1893, 1903-1905 e 1906-1909.</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal &#40;Constituinte&#41;, 1890-1893, SE, . Dt. Posse: 15/11/1890; Deputado Federal, 1903-1905, SE, . Dt. Posse: 06/05/1903; Deputado Federal, 1906-1909, SE, . Dt. Posse: 08/05/1906.</MANDATOSELETIVOS>
    <ATIVIDADESPARLAMENTARES>CD:&#10;MESA: 2&#186; Vice-Presidente, 1891.</ATIVIDADESPARLAMENTARES>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDECADASTRO>1804</IDECADASTRO>
    <MANDATOSCD>Deputado Federal, 1894-1896, AL, . Dt. Posse: 06/05/1894; Deputado Federal, 1912-1915, AL, . Dt. Posse: 22/05/1912.</MANDATOSCD>
    <MANDATOSEXTERNOS>Deputado Provincial, N/D, Partido: N/D,&#10;Per&#237;odo: 1888 a &#10;Senador Estadual, N/D, Partido: N/D,&#10;Per&#237;odo: 1893 a &#10;Deputado Estadual, AL, Partido: N/D,&#10;Per&#237;odo:  a </MANDATOSEXTERNOS>
    <CODPESSOA>119631</CODPESSOA>
    <TXTNOMEPARLAMENTAR>BARROS LINS</TXTNOMEPARLAMENTAR>
    <TXTNOME>Jos&#233; de Barros Albuquerque Lins</TXTNOME>
    <INDSEXO>M</INDSEXO>
    <NUMERODAULTIMALEGISLATURA>29</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>SEM PARTIDO</SIGPARTIDO>
    <SIGUFREPRESENTACAO>AL</SIGUFREPRESENTACAO>
    <DATNASCIMENTO>22/12/53</DATNASCIMENTO>
    <GRAUINSTRUCAO>Superior</GRAUINSTRUCAO>
    <NATURALIDADE>Camaragibe, AL</NATURALIDADE>
    <LEGISLATURAS>1894-1896 e 1912-1915.</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Estadual, , AL, ; Deputado Provincial, 1888-, , ; Senador Estadual, 1893-, , ; Deputado Federal, 1894-1896, AL, . Dt. Posse: 06/05/1894; Deputado Federal, 1912-1915, AL, . Dt. Posse: 22/05/1912.</MANDATOSELETIVOS>
    <RENUNCIAS>Renunciou em 1894.</RENUNCIAS>
    <ATIVIDADESPARTIDARIAS>Filiado ao partido liberal.</ATIVIDADESPARTIDARIAS>
    <ATIVIDADESPROFISSIONAIS>Juiz municipal do termo de S. Cruz, ES, depois removido para Christina, MG, e por fim para Penedo, AL; Propriet&#225;rio agr&#237;cola no munic&#237;pio de Porto-Cavalo.</ATIVIDADESPROFISSIONAIS>
    <ESTUDOSEGRAUSUNIVERSITARIOS>Direito, Faculdade de Recife, 1874.</ESTUDOSEGRAUSUNIVERSITARIOS>
    <OUTRASINFORMACOES>Foi Deputado &#224; Constituinte de Alagoas, fazendo parte da comiss&#227;o organizadora do projeto de constitui&#231;&#227;o. Finda a miss&#227;o constituinte, foi presidente da C&#226;mara. Mais tarde foi Senador estadual em 1893.</OUTRASINFORMACOES>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDECADASTRO>1809</IDECADASTRO>
    <MANDATOSCD>Deputado Federal, 1894-1896, AL, . Dt. Posse: 22/05/1894; Deputado Federal, 1897-1899, AL, . Dt. Posse: 20/05/1897; Deputado Federal, 1912-1913, AL, . Dt. Posse: 22/05/1912.</MANDATOSCD>
    <MANDATOSEXTERNOS>Senador Estadual, AL, Partido: N/D,&#10;Per&#237;odo: 1883 a </MANDATOSEXTERNOS>
    <CODPESSOA>119636</CODPESSOA>
    <TXTNOMEPARLAMENTAR>ROCHA CAVALCANTI</TXTNOMEPARLAMENTAR>
    <TXTNOME>Jos&#233; da Rocha Cavalcanti</TXTNOME>
    <INDSEXO>M</INDSEXO>
    <NUMCARTEIRAPARLAMENTAR>706</NUMCARTEIRAPARLAMENTAR>
    <NUMERODAULTIMALEGISLATURA>29</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>SEM PARTIDO</SIGPARTIDO>
    <SIGUFREPRESENTACAO>AL</SIGUFREPRESENTACAO>
    <DATNASCIMENTO>02/04/56</DATNASCIMENTO>
    <GRAUINSTRUCAO>Superior</GRAUINSTRUCAO>
    <NATURALIDADE>N&#227;o informado, AL</NATURALIDADE>
    <FILIACAO>Francisco da Rocha Cavalcanti e Francisca da Rocha Cavalcanti</FILIACAO>
    <LEGISLATURAS>1894-1896, 1897-1899 e 1912-1915.</LEGISLATURAS>
    <MANDATOSELETIVOS>Senador Estadual, 1883-, AL, ; Deputado Federal, 1894-1896, AL, . Dt. Posse: 22/05/1894; Deputado Federal, 1897-1899, AL, . Dt. Posse: 20/05/1897; Deputado Federal, 1912-1913, AL, . Dt. Posse: 22/05/1912.</MANDATOSELETIVOS>
    <ATIVIDADESPROFISSIONAIS>Juiz Municipal de S&#227;o Miguel de Campos, 1882-1886; Chefe de Pol&#237;cia de Alagoas.</ATIVIDADESPROFISSIONAIS>
    <ESTUDOSEGRAUSUNIVERSITARIOS>Bacharel em Direito pela Faculdade do Recife, 1880.</ESTUDOSEGRAUSUNIVERSITARIOS>
    <OUTRASINFORMACOES>Faleceu em janeiro de 1913.</OUTRASINFORMACOES>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDECADASTRO>1810</IDECADASTRO>
    <MANDATOSCD>Deputado Federal, 1894-1896, AM, . Dt. Posse: 06/05/1894; Deputado Federal, 1900-1902, AM, . Dt. Posse: 15/05/1900; Deputado Federal, 1903-1905, AM, . Dt. Posse: 03/06/1903.</MANDATOSCD>
    <CODPESSOA>119637</CODPESSOA>
    <TXTNOMEPARLAMENTAR>S&#193; PEIXOTO</TXTNOMEPARLAMENTAR>
    <TXTNOME>Antonio Gon&#231;alves  Pereira de S&#225; Peixoto</TXTNOME>
    <INDSEXO>M</INDSEXO>
    <NUMCARTEIRAPARLAMENTAR>749</NUMCARTEIRAPARLAMENTAR>
    <NUMERODAULTIMALEGISLATURA>26</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>SEM PARTIDO</SIGPARTIDO>
    <SIGUFREPRESENTACAO>AM</SIGUFREPRESENTACAO>
    <NATURALIDADE>, </NATURALIDADE>
    <LEGISLATURAS>1894-1896, 1900-1902 e 1903-1905.</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, 1894-1896, AM, . Dt. Posse: 06/05/1894; Deputado Federal, 1900-1902, AM, . Dt. Posse: 15/05/1900; Deputado Federal, 1903-1905, AM, . Dt. Posse: 03/06/1903.</MANDATOSELETIVOS>
    <ATIVIDADESPARLAMENTARES>CD:&#10;MESA: 2&#186; Suplente, 1894-1895.</ATIVIDADESPARLAMENTARES>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDECADASTRO>1811</IDECADASTRO>
    <MANDATOSCD>Deputado Federal, 1894-1896, BA, . Dt. Posse: 23/05/1894; Deputado Federal, 1897-1899, BA, . Dt. Posse: 03/05/1897.</MANDATOSCD>
    <CODPESSOA>119638</CODPESSOA>
    <TXTNOMEPARLAMENTAR>ARISTIDES DE QUEIROZ</TXTNOMEPARLAMENTAR>
    <TXTNOME>Aristides Galv&#227;o de Queiroz</TXTNOME>
    <INDSEXO>M</INDSEXO>
    <NUMCARTEIRAPARLAMENTAR>779</NUMCARTEIRAPARLAMENTAR>
    <NUMERODAULTIMALEGISLATURA>24</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>SEM PARTIDO</SIGPARTIDO>
    <SIGUFREPRESENTACAO>BA</SIGUFREPRESENTACAO>
    <GRAUINSTRUCAO>Superior</GRAUINSTRUCAO>
    <NATURALIDADE>N&#227;o Informado, BA</NATURALIDADE>
    <PROFISSOES>Engenheiro Civil</PROFISSOES>
    <LEGISLATURAS>1894-1896 e 1897-1899.</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, 1894-1896, BA, . Dt. Posse: 23/05/1894; Deputado Federal, 1897-1899, BA, . Dt. Posse: 03/05/1897.</MANDATOSELETIVOS>
    <ATIVIDADESPROFISSIONAIS>Professor, Imperial Instituto Bahiano de Agricultura; Engenheiro Chefe, Estrada de ferro Alto Muria&#233;.</ATIVIDADESPROFISSIONAIS>
    <ESTUDOSEGRAUSUNIVERSITARIOS>Matem&#225;tica e Ci&#234;ncias Naturais, Escola Central.</ESTUDOSEGRAUSUNIVERSITARIOS>
    <OBRASPUBLICADAS>QUEIROZ, Aristides Galv&#227;o de. Bases para organiza&#231;&#227;o de uma escola normal de agricultura na prov&#237;ncia da Bahia. Augusto Francisco Gonsalves &#40;colaborador&#41;. Bahia, 1880;&#10;______. S&#237;ntese universal e a teoria f&#237;sica, matem&#225;tica da raz&#227;o. Bahia, 1880;&#10;______. Observa&#231;&#245;es sobre alguns erros da moderna escola de barateza quilom&#233;trica, 1882.</OBRASPUBLICADAS>
    <OUTRASINFORMACOES>Membro do Instituto Polit&#233;cnico Brasileiro. Escreveu observa&#231;&#245;es sobre alguns erros da moderna escola da barateza kilom&#233;trica nas estradas de ferro para serem presentes ao Congresso de estrada de ferro do Brasil. Rio de Janeiro, 1882.</OUTRASINFORMACOES>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDECADASTRO>1816</IDECADASTRO>
    <MANDATOSCD>Deputado Federal, 1894-1896, BA, . Dt. Posse: 17/05/1894; Deputado Federal, 1897-1899, BA, . Dt. Posse: 03/05/1897; Deputado Federal, 1900-1902, BA, . Dt. Posse: 02/05/1900; Deputado Federal, 1903-1905, BA, . Dt. Posse: 02/05/1903.</MANDATOSCD>
    <CODPESSOA>119643</CODPESSOA>
    <TXTNOMEPARLAMENTAR>PARANHOS MONTENEGRO</TXTNOMEPARLAMENTAR>
    <TXTNOME>Thomaz Garcez Paranhos Montenegro</TXTNOME>
    <INDSEXO>M</INDSEXO>
    <NUMERODAULTIMALEGISLATURA>26</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>SEM PARTIDO</SIGPARTIDO>
    <SIGUFREPRESENTACAO>BA</SIGUFREPRESENTACAO>
    <NATURALIDADE>, </NATURALIDADE>
    <LEGISLATURAS>1894-1896, 1897-1899, 1900-1902 e 1903-1905.</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, 1894-1896, BA, . Dt. Posse: 17/05/1894; Deputado Federal, 1897-1899, BA, . Dt. Posse: 03/05/1897; Deputado Federal, 1900-1902, BA, . Dt. Posse: 02/05/1900; Deputado Federal, 1903-1905, BA, . Dt. Posse: 02/05/1903.</MANDATOSELETIVOS>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDECADASTRO>1817</IDECADASTRO>
    <MANDATOSCD>Deputado Federal, 1894-1896, BA, . Dt. Posse: 23/05/1894; Deputado Federal, 1897-1899, BA, . Dt. Posse: 04/05/1897; Deputado Federal, 1900-1902, BA, . Dt. Posse: 02/05/1900; Deputado Federal, 1903-1905, BA, . Dt. Posse: 03/05/1903; Deputado Federal, 1909-1912, BA, . Dt. Posse: 03/05/1909; Deputado Federal, 1912-1915, BA, . Dt. Posse: 07/05/1912; Deputado Federal, 1915-1918, BA, . Dt. Posse: 15/05/1915; Deputado Federal, 1918-1921, BA, . Dt. Posse: 04/05/1918.</MANDATOSCD>
    <CODPESSOA>119644</CODPESSOA>
    <TXTNOMEPARLAMENTAR>RODRIGUES LIMA</TXTNOMEPARLAMENTAR>
    <TXTNOME>Antonio Rodrigues  Lima</TXTNOME>
    <INDSEXO>M</INDSEXO>
    <NUMERODAULTIMALEGISLATURA>31</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>SEM PARTIDO</SIGPARTIDO>
    <SIGUFREPRESENTACAO>BA</SIGUFREPRESENTACAO>
    <NATURALIDADE>, </NATURALIDADE>
    <LEGISLATURAS>1894-1896, 1897-1899, 1900-1902, 1903-1905, 1909-1912, 1912-1915, 1915-1918 e 1918-1921.</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, 1894-1896, BA, . Dt. Posse: 23/05/1894; Deputado Federal, 1897-1899, BA, . Dt. Posse: 04/05/1897; Deputado Federal, 1900-1902, BA, . Dt. Posse: 02/05/1900; Deputado Federal, 1903-1905, BA, . Dt. Posse: 03/05/1903; Deputado Federal, 1909-1912, BA, . Dt. Posse: 03/05/1909; Deputado Federal, 1912-1915, BA, . Dt. Posse: 07/05/1912; Deputado Federal, 1915-1918, BA, . Dt. Posse: 15/05/1915; Deputado Federal, 1918-1921, BA, . Dt. Posse: 04/05/1918.</MANDATOSELETIVOS>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDECADASTRO>1818</IDECADASTRO>
    <MANDATOSCD>Deputado Federal, 1894-1896, BA, . Dt. Posse: 04/06/1894.</MANDATOSCD>
    <CODPESSOA>119645</CODPESSOA>
    <TXTNOMEPARLAMENTAR>SEBASTI&#195;O LANDULFO</TXTNOMEPARLAMENTAR>
    <TXTNOME>Sebasti&#227;o Landulpho da Rocha Medrado</TXTNOME>
    <INDSEXO>M</INDSEXO>
    <NUMCARTEIRAPARLAMENTAR>834</NUMCARTEIRAPARLAMENTAR>
    <NUMERODAULTIMALEGISLATURA>23</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>SEM PARTIDO</SIGPARTIDO>
    <SIGUFREPRESENTACAO>BA</SIGUFREPRESENTACAO>
    <NATURALIDADE>, </NATURALIDADE>
    <LEGISLATURAS>1894-1896</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, 1894-1896, BA, . Dt. Posse: 04/06/1894.</MANDATOSELETIVOS>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDECADASTRO>1819</IDECADASTRO>
    <MANDATOSCD>Deputado Federal, 1894-1896, BA, . Dt. Posse: 23/05/1894; Deputado Federal, 1897-1899, BA, . Dt. Posse: 03/05/1897; Deputado Federal, 1900-1902, BA, . Dt. Posse: 02/05/1900; Deputado Federal, 1903-1905, BA, . Dt. Posse: 03/05/1903.</MANDATOSCD>
    <CODPESSOA>119646</CODPESSOA>
    <TXTNOMEPARLAMENTAR>TOLENTINO DOS SANTOS</TXTNOMEPARLAMENTAR>
    <TXTNOME>Nicol&#225;o  Tolentino dos Santos</TXTNOME>
    <INDSEXO>M</INDSEXO>
    <NUMCARTEIRAPARLAMENTAR>815</NUMCARTEIRAPARLAMENTAR>
    <NUMERODAULTIMALEGISLATURA>26</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>SEM PARTIDO</SIGPARTIDO>
    <SIGUFREPRESENTACAO>BA</SIGUFREPRESENTACAO>
    <NATURALIDADE>, </NATURALIDADE>
    <LEGISLATURAS>1894-1896, 1897-1899, 1900-1902 e 1903-1905.</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, 1894-1896, BA, . Dt. Posse: 23/05/1894; Deputado Federal, 1897-1899, BA, . Dt. Posse: 03/05/1897; Deputado Federal, 1900-1902, BA, . Dt. Posse: 02/05/1900; Deputado Federal, 1903-1905, BA, . Dt. Posse: 03/05/1903.</MANDATOSELETIVOS>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDECADASTRO>1820</IDECADASTRO>
    <MANDATOSCD>Deputado Federal, 1894-1893, BA, . Dt. Posse: 16/05/1894; Deputado Federal, 1897-1899, BA, . Dt. Posse: 03/05/1897; Deputado Federal, 1900-1902, BA, . Dt. Posse: 02/05/1900; Deputado Federal, 1903-1905, BA, . Dt. Posse: 02/05/1903.</MANDATOSCD>
    <CODPESSOA>119647</CODPESSOA>
    <TXTNOMEPARLAMENTAR>VERGNE DE ABREU</TXTNOMEPARLAMENTAR>
    <TXTNOME>Pedro Vergne de Abreu</TXTNOME>
    <INDSEXO>M</INDSEXO>
    <NUMERODAULTIMALEGISLATURA>26</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>SEM PARTIDO</SIGPARTIDO>
    <SIGUFREPRESENTACAO>BA</SIGUFREPRESENTACAO>
    <GRAUINSTRUCAO>Superior</GRAUINSTRUCAO>
    <NATURALIDADE>, </NATURALIDADE>
    <PROFISSOES>Advogado</PROFISSOES>
    <LEGISLATURAS>1891-1893, 1897-1899, 1900-1902 e 1903-1905.</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, 1894-1893, BA, . Dt. Posse: 16/05/1894; Deputado Federal, 1897-1899, BA, . Dt. Posse: 03/05/1897; Deputado Federal, 1900-1902, BA, . Dt. Posse: 02/05/1900; Deputado Federal, 1903-1905, BA, . Dt. Posse: 02/05/1903.</MANDATOSELETIVOS>
    <ESTUDOSEGRAUSUNIVERSITARIOS>Ci&#234;ncias Sociais e Jur&#237;dicas, Faculdade do Recife.</ESTUDOSEGRAUSUNIVERSITARIOS>
    <OBRASPUBLICADAS>ABREU, Pedro Vergne de. Confer&#234;ncia abolicionista. Recife, 1882, 25 p.</OBRASPUBLICADAS>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDECADASTRO>1822</IDECADASTRO>
    <MANDATOSCD>Deputado Federal, 1894-1893, CE, . Dt. Posse: 06/05/1894.</MANDATOSCD>
    <MANDATOSEXTERNOS>Deputado Provincial, N/D, Partido: N/D,&#10;Per&#237;odo:  a </MANDATOSEXTERNOS>
    <CODPESSOA>119649</CODPESSOA>
    <TXTNOMEPARLAMENTAR>GON&#199;ALO DE LAGOS</TXTNOMEPARLAMENTAR>
    <TXTNOME>Gon&#231;alo de Lagos Fernandes Bastos</TXTNOME>
    <INDSEXO>M</INDSEXO>
    <NUMERODAULTIMALEGISLATURA>22</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>SEM PARTIDO</SIGPARTIDO>
    <SIGUFREPRESENTACAO>CE</SIGUFREPRESENTACAO>
    <DATNASCIMENTO>16/11/42</DATNASCIMENTO>
    <GRAUINSTRUCAO>Superior</GRAUINSTRUCAO>
    <NATURALIDADE>, </NATURALIDADE>
    <LEGISLATURAS>1891-1893</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Provincial, , , ; Deputado Federal, 1894-1893, CE, . Dt. Posse: 06/05/1894.</MANDATOSELETIVOS>
    <ESTUDOSEGRAUSUNIVERSITARIOS>Direito, Faculdade do Recife, 1865.</ESTUDOSEGRAUSUNIVERSITARIOS>
    <OUTRASINFORMACOES>Filho do desembargador Andr&#233; Bastos de Oliveira. Abolicionista, foi representante da imprensa cearense na sess&#227;o solene da liberta&#231;&#227;o dos escravos de Fortaleza.</OUTRASINFORMACOES>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDECADASTRO>1824</IDECADASTRO>
    <MANDATOSCD>Deputado Federal, 1894-1896, CE, . Dt. Posse: 06/05/1894; Deputado Federal, 1897-1899, CE, . Dt. Posse: 03/05/1897.</MANDATOSCD>
    <CODPESSOA>119651</CODPESSOA>
    <TXTNOMEPARLAMENTAR>ILDEFONSO LIMA</TXTNOMEPARLAMENTAR>
    <TXTNOME>Ildefonso Corr&#234;a Lima</TXTNOME>
    <INDSEXO>M</INDSEXO>
    <NUMERODAULTIMALEGISLATURA>24</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>SEM PARTIDO</SIGPARTIDO>
    <SIGUFREPRESENTACAO>CE</SIGUFREPRESENTACAO>
    <NATURALIDADE>, </NATURALIDADE>
    <LEGISLATURAS>1894-1896 e 1897-1899.</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, 1894-1896, CE, . Dt. Posse: 06/05/1894; Deputado Federal, 1897-1899, CE, . Dt. Posse: 03/05/1897.</MANDATOSELETIVOS>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDECADASTRO>1825</IDECADASTRO>
    <MANDATOSCD>Deputado Federal, 1894-1896, CE, . Dt. Posse: 06/05/1894; Deputado Federal, 1897-1899, CE, . Dt. Posse: 03/05/1897; Deputado Federal, 1900-1902, CE, . Dt. Posse: 02/05/1900.</MANDATOSCD>
    <CODPESSOA>119652</CODPESSOA>
    <TXTNOMEPARLAMENTAR>PEDRO BORGES</TXTNOMEPARLAMENTAR>
    <TXTNOME>Pedro Agusto Borges</TXTNOME>
    <INDSEXO>M</INDSEXO>
    <NUMERODAULTIMALEGISLATURA>25</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>SEM PARTIDO</SIGPARTIDO>
    <SIGUFREPRESENTACAO>CE</SIGUFREPRESENTACAO>
    <NATURALIDADE>, </NATURALIDADE>
    <LEGISLATURAS>1894-1896, 1897-1899 e 1900-1902.</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, 1894-1896, CE, . Dt. Posse: 06/05/1894; Deputado Federal, 1897-1899, CE, . Dt. Posse: 03/05/1897; Deputado Federal, 1900-1902, CE, . Dt. Posse: 02/05/1900.</MANDATOSELETIVOS>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDECADASTRO>1826</IDECADASTRO>
    <MANDATOSCD>Deputado Federal, 1896, CE, ; Deputado Federal, 1901-1902, CE, . Dt. Posse: 22/10/1901; Deputado Federal, 1903-1905, CE, . Dt. Posse: 02/05/1903; Deputado Federal, 1906-1909, CE, . Dt. Posse: 04/05/1906; Deputado Federal, 1910-1912, CE, . Dt. Posse: 19/11/1910; Deputado Federal, 1912-1915, CE, . Dt. Posse: 18/07/1912; Deputado Federal, 1918-1921, CE, . Dt. Posse: 03/05/1918.</MANDATOSCD>
    <CODPESSOA>119653</CODPESSOA>
    <TXTNOMEPARLAMENTAR>TOM&#193;S CAVALCANTI</TXTNOMEPARLAMENTAR>
    <TXTNOME>Thomaz Cavalcanti de Albuquerque</TXTNOME>
    <INDSEXO>M</INDSEXO>
    <NUMCARTEIRAPARLAMENTAR>721</NUMCARTEIRAPARLAMENTAR>
    <NUMERODAULTIMALEGISLATURA>31</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>SEM PARTIDO</SIGPARTIDO>
    <SIGUFREPRESENTACAO>CE</SIGUFREPRESENTACAO>
    <NATURALIDADE>, </NATURALIDADE>
    <LEGISLATURAS>1894-1896, 1900-1902, 1903-1905, 1906-1909, 1909-1912, 1912-1915 e 1918-1921.</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, -1896, CE, ; Deputado Federal, 1901-1902, CE, . Dt. Posse: 22/10/1901; Deputado Federal, 1903-1905, CE, . Dt. Posse: 02/05/1903; Deputado Federal, 1906-1909, CE, . Dt. Posse: 04/05/1906; Deputado Federal, 1910-1912, CE, . Dt. Posse: 19/11/1910; Deputado Federal, 1912-1915, CE, . Dt. Posse: 18/07/1912; Deputado Federal, 1918-1921, CE, . Dt. Posse: 03/05/1918.</MANDATOSELETIVOS>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDECADASTRO>1827</IDECADASTRO>
    <MANDATOSCD>Deputado Federal, 1894-1896, DF, . Dt. Posse: 11/05/1894.</MANDATOSCD>
    <CODPESSOA>119654</CODPESSOA>
    <TXTNOMEPARLAMENTAR>AM&#201;RICO DE MATOS</TXTNOMEPARLAMENTAR>
    <TXTNOME>Jos&#233; Americo de Mattos</TXTNOME>
    <INDSEXO>M</INDSEXO>
    <NUMERODAULTIMALEGISLATURA>23</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>SEM PARTIDO</SIGPARTIDO>
    <SIGUFREPRESENTACAO>DF</SIGUFREPRESENTACAO>
    <GRAUINSTRUCAO>Superior</GRAUINSTRUCAO>
    <NATURALIDADE>N&#227;o informado, RJ</NATURALIDADE>
    <LEGISLATURAS>1894-1896</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, 1894-1896, DF, . Dt. Posse: 11/05/1894.</MANDATOSELETIVOS>
    <ATIVIDADESPROFISSIONAIS>Alferes aluno em 19 de janeiro de 1889, foi promovido a 2&#186; tenente a 4 de Janeiro de 1890, 1&#186; a 7 de Janeiro, a capit&#227;o em 13 de Janeiro de 1892.</ATIVIDADESPROFISSIONAIS>
    <ESTUDOSEGRAUSUNIVERSITARIOS>Engenharia pelo regulamento de 1889.</ESTUDOSEGRAUSUNIVERSITARIOS>
    <OUTRASINFORMACOES>Serviu algum tempo na Estrada de Ferro Central do Brasil.</OUTRASINFORMACOES>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDECADASTRO>1828</IDECADASTRO>
    <MANDATOSCD>Deputado Federal, 1894-1896, DF, . Dt. Posse: 06/05/1894.</MANDATOSCD>
    <CODPESSOA>119655</CODPESSOA>
    <TXTNOMEPARLAMENTAR>ANT&#212;NIO DE SIQUEIRA</TXTNOMEPARLAMENTAR>
    <TXTNOME>Antonio Jos&#233; de Siqueira</TXTNOME>
    <INDSEXO>M</INDSEXO>
    <NUMERODAULTIMALEGISLATURA>23</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>SEM PARTIDO</SIGPARTIDO>
    <SIGUFREPRESENTACAO>DF</SIGUFREPRESENTACAO>
    <GRAUINSTRUCAO>Superior</GRAUINSTRUCAO>
    <NATURALIDADE>, </NATURALIDADE>
    <LEGISLATURAS>1894-1896</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, 1894-1896, DF, . Dt. Posse: 06/05/1894.</MANDATOSELETIVOS>
    <ATIVIDADESPROFISSIONAIS>Professor, Curso Geral da Escola Militar.</ATIVIDADESPROFISSIONAIS>
    <ESTUDOSEGRAUSUNIVERSITARIOS>Curso de engenharia pelo regulamento de 1874; Bacharel em matem&#225;tica e ci&#234;ncias f&#237;sicas.</ESTUDOSEGRAUSUNIVERSITARIOS>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDECADASTRO>1830</IDECADASTRO>
    <MANDATOSCD>Deputado Federal, 1894-1896, DF, . Dt. Posse: 06/05/1894.</MANDATOSCD>
    <CODPESSOA>119657</CODPESSOA>
    <TXTNOMEPARLAMENTAR>LINS DE VASCONCELOS</TXTNOMEPARLAMENTAR>
    <TXTNOME>C&#226;ndido de Oliveira Lins de Vasconcellos</TXTNOME>
    <INDSEXO>M</INDSEXO>
    <NUMERODAULTIMALEGISLATURA>23</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>SEM PARTIDO</SIGPARTIDO>
    <SIGUFREPRESENTACAO>DF</SIGUFREPRESENTACAO>
    <NATURALIDADE>, </NATURALIDADE>
    <LEGISLATURAS>1894-1896</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, 1894-1896, DF, . Dt. Posse: 06/05/1894.</MANDATOSELETIVOS>
    <ATIVIDADESPARLAMENTARES>CD:&#10;MESA: 1&#186; Secret&#225;rio, 1896.</ATIVIDADESPARLAMENTARES>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDECADASTRO>1831</IDECADASTRO>
    <MANDATOSCD>Deputado Federal, 1894-1896, DF, . Dt. Posse: 09/05/1894; Deputado Federal, 1897-1899, DF, . Dt. Posse: 03/05/1897; Deputado Federal, 1900-1902, DF, . Dt. Posse: 07/06/1900; Deputado Federal, 1903-1905, DF, . Dt. Posse: 17/12/1903.</MANDATOSCD>
    <CODPESSOA>119658</CODPESSOA>
    <TXTNOMEPARLAMENTAR>OSCAR GOD&#211;I</TXTNOMEPARLAMENTAR>
    <TXTNOME>Oscar de Godoy</TXTNOME>
    <INDSEXO>M</INDSEXO>
    <NUMCARTEIRAPARLAMENTAR>817</NUMCARTEIRAPARLAMENTAR>
    <NUMERODAULTIMALEGISLATURA>26</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>SEM PARTIDO</SIGPARTIDO>
    <SIGUFREPRESENTACAO>DF</SIGUFREPRESENTACAO>
    <NATURALIDADE>, </NATURALIDADE>
    <LEGISLATURAS>1894-1896, 1897-1899, 1900-1902 e 1903-1905.</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, 1894-1896, DF, . Dt. Posse: 09/05/1894; Deputado Federal, 1897-1899, DF, . Dt. Posse: 03/05/1897; Deputado Federal, 1900-1902, DF, . Dt. Posse: 07/06/1900; Deputado Federal, 1903-1905, DF, . Dt. Posse: 17/12/1903.</MANDATOSELETIVOS>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDECADASTRO>1832</IDECADASTRO>
    <MANDATOSCD>Deputado Federal, 1895-1896, DF, . Dt. Posse: 20/11/1895; Deputado Federal, 1897-1899, DF, . Dt. Posse: 03/05/1897.</MANDATOSCD>
    <CODPESSOA>119659</CODPESSOA>
    <TXTNOMEPARLAMENTAR>TIMOTHEO DA COSTA</TXTNOMEPARLAMENTAR>
    <TXTNOME>Manoel Timotheo da Costa</TXTNOME>
    <INDSEXO>M</INDSEXO>
    <NUMCARTEIRAPARLAMENTAR>829</NUMCARTEIRAPARLAMENTAR>
    <NUMERODAULTIMALEGISLATURA>24</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>SEM PARTIDO</SIGPARTIDO>
    <SIGUFREPRESENTACAO>DF</SIGUFREPRESENTACAO>
    <NATURALIDADE>, </NATURALIDADE>
    <LEGISLATURAS>1894-1896 e 1897-1899.</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, 1895-1896, DF, . Dt. Posse: 20/11/1895; Deputado Federal, 1897-1899, DF, . Dt. Posse: 03/05/1897.</MANDATOSELETIVOS>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDECADASTRO>1833</IDECADASTRO>
    <MANDATOSCD>Deputado Federal &#40;Constituinte&#41;, 1890-1893, DF, . Dt. Posse: 15/11/1890; Deputado Federal, 1894-1896, DF, . Dt. Posse: 03/05/1894; Deputado Federal, 1912-1915, DF, . Dt. Posse: 09/05/1912; Deputado Federal, 1915-1918, DF, . Dt. Posse: 19/06/1915.</MANDATOSCD>
    <MANDATOSEXTERNOS>Senador, DF, Partido: N/D,&#10;Per&#237;odo: 1896 a 1897&#10;Senador, DF, Partido: N/D,&#10;Per&#237;odo: 1897 a 1906</MANDATOSEXTERNOS>
    <CODPESSOA>119454</CODPESSOA>
    <TXTNOMEPARLAMENTAR>THOMAZ DELFINO</TXTNOMEPARLAMENTAR>
    <TXTNOME>Thomaz Delfino dos Santos</TXTNOME>
    <INDSEXO>M</INDSEXO>
    <NUMERODAULTIMALEGISLATURA>30</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>SEM PARTIDO</SIGPARTIDO>
    <SIGUFREPRESENTACAO>DF</SIGUFREPRESENTACAO>
    <DATNASCIMENTO>24/09/60</DATNASCIMENTO>
    <GRAUINSTRUCAO>Superior</GRAUINSTRUCAO>
    <NATURALIDADE>Rio de Janeiro, RJ</NATURALIDADE>
    <PROFISSOES>M&#233;dico</PROFISSOES>
    <LEGISLATURAS>1891-1893, 1894-1896, 1912-1915 e 1915-1918.</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal &#40;Constituinte&#41;, 1890-1893, DF, . Dt. Posse: 15/11/1890; Deputado Federal, 1894-1896, DF, . Dt. Posse: 03/05/1894; Senador, 1896-1897, DF, ; Senador, 1897-1906, DF, ; Deputado Federal, 1912-1915, DF, . Dt. Posse: 09/05/1912; Deputado Federal, 1915-1918, DF, . Dt. Posse: 19/06/1915.</MANDATOSELETIVOS>
    <ESTUDOSEGRAUSUNIVERSITARIOS>Doutor em Medicina, Faculdade do Rio de Janeiro.</ESTUDOSEGRAUSUNIVERSITARIOS>
    <ATIVIDADESPARLAMENTARES>CD:&#10;MESA: 1&#186; Secret&#225;rio, 1894-1895; 3&#186; Secret&#225;rio, 1893.</ATIVIDADESPARLAMENTARES>
    <OBRASPUBLICADAS>SANTOS, Thomaz Delphino dos. Que melhoramentos materiais devem ser introduzidos na cidade do Rio de Janeiro para torn&#225;-la mais salubre&#63;. Rio de Janeiro, 1882. Tese apresentada &#224; Faculdade de Medicina para obter o grau de Doutor;&#10;______. Discurso pronunciado no Ato solene da Colla&#231;&#227;o de Grau aos doutorandos de 1882 na augusta presen&#231;a de SS. MM. e AA. Imperiais em resposta ao diretor da Faculdade. Rio de Janeiro, 1882.&#10;</OBRASPUBLICADAS>
    <FORMATODATANASCIMENTO>1</FORMATODATANASCIMENTO>
  </DATA_RECORD>
  <DATA_RECORD>
    <IDECADASTRO>1835</IDECADASTRO>
    <MANDATOSCD>Deputado Federal, 1894-1896, ES, . Dt. Posse: 17/05/1894; Deputado Federal, 1897-1899, ES, . Dt. Posse: 08/06/1897; Deputado Federal, 1900-1902, ES, . Dt. Posse: 02/05/1900; Deputado Federal, 1903-1905, ES, . Dt. Posse: 02/05/1903.</MANDATOSCD>
    <CODPESSOA>119662</CODPESSOA>
    <TXTNOMEPARLAMENTAR>GALDINO LORETO</TXTNOMEPARLAMENTAR>
    <TXTNOME>Galdino Teixeira Lins de Barros Loreto</TXTNOME>
    <INDSEXO>M</INDSEXO>
    <NUMERODAULTIMALEGISLATURA>26</NUMERODAULTIMALEGISLATURA>
    <SIGPARTIDO>SEM PARTIDO</SIGPARTIDO>
    <SIGUFREPRESENTACAO>ES</SIGUFREPRESENTACAO>
    <GRAUINSTRUCAO>Superior</GRAUINSTRUCAO>
    <NATURALIDADE>N&#227;o informado, PE</NATURALIDADE>
    <LEGISLATURAS>1894-1896, 1897-1899, 1900-1902 e 1903-1905.</LEGISLATURAS>
    <MANDATOSELETIVOS>Deputado Federal, 1894-1896, ES, . Dt. Posse: 17/05/1894; Deputado Federal, 1897-1899, ES, . Dt. Posse: 08/06/1897; Deputado Federal, 1900-1902, ES, . Dt. Posse: 02/05/1900; Deputado Federal, 1903-1905, ES, . Dt. Posse: 02/05/1903.</MANDATOSELETIVOS>